name: kanhamusic
services:
  - name: kanhamusic
    type: worker
    git:
      repository: Oyekanhaa/KanhaMusic
      branch: dev
      builder: dockerfile
      dockerfile: Dockerfile
    env:
      - key: API_ID
        value: ""
      - key: API_HASH
        value: ""
      - key: TOKEN
        value: ""
      - key: MONGO_DB_URI
        value: ""
      - key: STRING_SESSION
        value: ""
      - key: OWNER_ID
        value: ""
