/*
 * ● KanhaMusic
 * ○ A high-performance engine for streaming music in Telegram voicechats.
 *
 * Copyright (C) 2026 Kanha
 *
 * This program is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * Repository: https://github.com/Oyekanhaa/KanhaMusic
 */

package models

import (
	"context"
	"regexp"
	"strings"
	"unicode"

	td "github.com/Kanha/Meow"
)

type (
	PlatformName string

	Track struct {
		ID        string       // track unique id
		Title     string       // title
		Duration  int          // track duration in seconds
		Artwork   string       // thumbnail url of the track
		URL       string       // track url
		Requester string       // html mention or @username who requested this track
		Video       bool         // whether this track will be played as video
		Source      PlatformName // unique PlatformName
		IsAutoplay  bool         // whether this track was generated by autoplay
		EngineToken string       // internal validation token for autoplay
	}

	// Platform defines the common contract for all supported platforms
	// (e.g. YouTube, Spotify, Telegram). Each platform is responsible for
	// deciding whether it can resolve and download tracks from a query.
	Platform interface {
		// Name returns the unique identifier of the platform.
		Name() PlatformName

		// Priority returns the priority of this platform when multiple
		// platforms could handle the same query. Higher values take precedence.
		Priority() int

		// CanGet reports whether this platform can resolve
		// tracks from the given query or search term.
		CanGet(query string) bool

		// Get fetches track metadata for the given query.
		//
		// video indicates whether video playback is requested.
		// Platforms that do not support video should still return tracks,
		// but must leave Track.Video false.
		Get(query string, video bool) ([]*Track, error)

		// CanDownload reports whether this platform can download tracks
		// originating from the given source platform.
		CanDownload(source PlatformName) bool

		// Download downloads the given track and returns the local file path.
		//
		// ctx is used for cancellation and timeouts.
		// track is the track to download.
		// msg is used to send progress updates (if not nil).
		Download(ctx context.Context, track *Track, msg *td.Message) (string, error)
	}
)

var cleanTitleRegex = regexp.MustCompile(`[\(\[\{].*?[\)\]\}]`)

// MarkAutoplay sets autoplay metadata and validation token on the track.
func (t *Track) MarkAutoplay(requester, token string) {
	if t == nil {
		return
	}
	t.IsAutoplay = true
	t.Requester = requester
	t.EngineToken = token
}

// IsVerifiedAutoplay checks if this track was flagged by autoplay engine.
func (t *Track) IsVerifiedAutoplay(token string) bool {
	if t == nil || !t.IsAutoplay {
		return false
	}
	if token != "" && t.EngineToken != token {
		return false
	}
	return true
}

// NormalizeTrackTitle cleans up a song title to prevent duplicate plays.
func NormalizeTrackTitle(title string) string {
	if title == "" {
		return ""
	}
	s := strings.ToLower(title)
	s = cleanTitleRegex.ReplaceAllString(s, " ")

	// Strip common redundant qualifiers
	replacements := []string{
		"official music video", "official video", "music video",
		"lyric video", "lyrics", "full video", "video song",
		"audio song", "audio track", "official audio", "audio",
		"4k", "8k", "hd", "remix", "song", "full track",
	}
	for _, rep := range replacements {
		s = strings.ReplaceAll(s, rep, " ")
	}

	var b strings.Builder
	for _, r := range s {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || unicode.IsSpace(r) {
			b.WriteRune(r)
		} else {
			b.WriteRune(' ')
		}
	}

	fields := strings.Fields(b.String())
	return strings.Join(fields, " ")
}

