// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package gotdbot

// AcceptOauthRequestOpts contains optional parameters for AcceptOauthRequest
type AcceptOauthRequestOpts struct {
	// Pass true if the current user allowed the bot that was returned in getOauthLinkInfo, to access their phone number
	AllowPhoneNumberAccess bool
	// Pass true if the current user allowed the bot that was returned in getOauthLinkInfo, to send them messages
	AllowWriteAccess bool
}

// AddContactOpts contains optional parameters for AddContact
type AddContactOpts struct {
	// The contact to add or edit; phone number may be empty and needs to be specified only if known
	Contact *ImportedContact
	// Pass true to share the current user's phone number with the new contact. A corresponding rule to userPrivacySettingShowPhoneNumber will be added if needed.
	SharePhoneNumber bool
}

// AddLocalMessageOpts contains optional parameters for AddLocalMessage
type AddLocalMessageOpts struct {
	// Pass true to disable notification for the message
	DisableNotification bool
	// Information about the message or story to be replied; pass null if none
	ReplyTo InputMessageReplyTo
}

// AddMessageReactionOpts contains optional parameters for AddMessageReaction
type AddMessageReactionOpts struct {
	// Pass true if the reaction is added with a big animation
	IsBig bool
	// Pass true if the reaction needs to be added to recent reactions; tags are never added to the list of recent reactions
	UpdateRecentReactions bool
}

// AddPendingPaidMessageReactionOpts contains optional parameters for AddPendingPaidMessageReaction
type AddPendingPaidMessageReactionOpts struct {
	// Type of the paid reaction; pass null if the user didn't choose reaction type explicitly, for example, the reaction is set from the message bubble
	Type PaidReactionType
}

// AddProxyOpts contains optional parameters for AddProxy
type AddProxyOpts struct {
	// Pass true to immediately enable the proxy
	Enable bool
}

// AddQuickReplyShortcutInlineQueryResultMessageOpts contains optional parameters for AddQuickReplyShortcutInlineQueryResultMessage
type AddQuickReplyShortcutInlineQueryResultMessageOpts struct {
	// Pass true to hide the bot, via which the message is sent. Can be used only for bots getOption("animation_search_bot_username"), getOption("photo_search_bot_username"), and getOption("venue_search_bot_username")
	HideViaBot bool
}

// AddRecentStickerOpts contains optional parameters for AddRecentSticker
type AddRecentStickerOpts struct {
	// Pass true to add the sticker to the list of stickers recently attached to photo or video files; pass false to add the sticker to the list of recently sent stickers
	IsAttached bool
}

// AddWebBrowserSettingsExceptionOpts contains optional parameters for AddWebBrowserSettingsException
type AddWebBrowserSettingsExceptionOpts struct {
	// Pass true if the specified website must be opened in an external browser; pass false to open it in the in-app browser. There can be at most 100 exceptions in each list of the exceptions
	OpenExternalBrowser bool
}

// AllowUnpaidMessagesFromUserOpts contains optional parameters for AllowUnpaidMessagesFromUser
type AllowUnpaidMessagesFromUserOpts struct {
	// Pass true to refund the user previously paid messages
	RefundPayments bool
}

// AnswerCallbackQueryOpts contains optional parameters for AnswerCallbackQuery
type AnswerCallbackQueryOpts struct {
	// Pass true to show an alert to the user instead of a toast notification
	ShowAlert bool
}

// AnswerInlineQueryOpts contains optional parameters for AnswerInlineQuery
type AnswerInlineQueryOpts struct {
	// Button to be shown above inline query results; pass null if none
	Button *InlineQueryResultsButton
	// Pass true if results may be cached and returned only for the user who sent the query. By default, results may be returned to any user who sends the same query
	IsPersonal bool
}

// BanChatMemberOpts contains optional parameters for BanChatMember
type BanChatMemberOpts struct {
	// Pass true to delete all messages in the chat for the user who is being removed. Always true for supergroups and channels
	RevokeMessages bool
}

// BlockMessageSenderFromRepliesOpts contains optional parameters for BlockMessageSenderFromReplies
type BlockMessageSenderFromRepliesOpts struct {
	// Pass true to delete all messages from the same sender
	DeleteAllMessages bool
	// Pass true to delete the message
	DeleteMessage bool
	// Pass true to report the sender to the Telegram moderators
	ReportSpam bool
}

// CancelDownloadFileOpts contains optional parameters for CancelDownloadFile
type CancelDownloadFileOpts struct {
	// Pass true to stop downloading only if it hasn't been started, i.e. request hasn't been sent to server
	OnlyIfPending bool
}

// CanSendMessageToUserOpts contains optional parameters for CanSendMessageToUser
type CanSendMessageToUserOpts struct {
	// Pass true to get only locally available information without sending network requests
	OnlyLocal bool
}

// ChangeStickerSetOpts contains optional parameters for ChangeStickerSet
type ChangeStickerSetOpts struct {
	// The new value of is_archived. A sticker set can't be installed and archived simultaneously
	IsArchived bool
	// The new value of is_installed
	IsInstalled bool
}

// ChangeWebBrowserSettingsOpts contains optional parameters for ChangeWebBrowserSettings
type ChangeWebBrowserSettingsOpts struct {
	// Pass true if a close button must be shown in the in-app browser; for Android app only
	DisplayCloseButton bool
	// Pass true if links must be opened in an external browser by default
	OpenExternalBrowser bool
}

// ClearAllDraftMessagesOpts contains optional parameters for ClearAllDraftMessages
type ClearAllDraftMessagesOpts struct {
	// Pass true to keep local message drafts in secret chats
	ExcludeSecretChats bool
}

// ClearRecentStickersOpts contains optional parameters for ClearRecentStickers
type ClearRecentStickersOpts struct {
	// Pass true to clear the list of stickers recently attached to photo or video files; pass false to clear the list of recently sent stickers
	IsAttached bool
}

// ClearSearchedForTagsOpts contains optional parameters for ClearSearchedForTags
type ClearSearchedForTagsOpts struct {
	// Pass true to clear the list of recently searched for cashtags; otherwise, the list of recently searched for hashtags will be cleared
	ClearCashtags bool
}

// ClickChatSponsoredMessageOpts contains optional parameters for ClickChatSponsoredMessage
type ClickChatSponsoredMessageOpts struct {
	// Pass true if the user expanded the video from the sponsored message fullscreen before the click
	FromFullscreen bool
	// Pass true if the media was clicked in the sponsored message
	IsMediaClick bool
}

// ComposeRichMessageWithAiOpts contains optional parameters for ComposeRichMessageWithAi
type ComposeRichMessageWithAiOpts struct {
	// Pass true to add emoji to the text
	AddEmojis bool
}

// ComposeTextWithAiOpts contains optional parameters for ComposeTextWithAi
type ComposeTextWithAiOpts struct {
	// Pass true to add emoji to the text
	AddEmojis bool
}

// CreateBasicGroupChatOpts contains optional parameters for CreateBasicGroupChat
type CreateBasicGroupChatOpts struct {
	// Pass true to create the chat without a network request. In this case all information about the chat except its type, title and photo can be incorrect
	Force bool
}

// CreateBotOpts contains optional parameters for CreateBot
type CreateBotOpts struct {
	// Pass true if the bot is created from an internalLinkTypeRequestManagedBot link
	ViaLink bool
}

// CreateCallOpts contains optional parameters for CreateCall
type CreateCallOpts struct {
	// Pass true to create a video call
	IsVideo bool
}

// CreateChatInviteLinkOpts contains optional parameters for CreateChatInviteLink
type CreateChatInviteLinkOpts struct {
	// Pass true if users joining the chat via the link need to be approved by chat administrators. In this case, member_limit must be 0
	CreatesJoinRequest bool
}

// CreateCommunityOpts contains optional parameters for CreateCommunity
type CreateCommunityOpts struct {
	// Pass true if the chat will be visible only to administrators of the community
	IsChatHidden bool
}

// CreateForumTopicOpts contains optional parameters for CreateForumTopic
type CreateForumTopicOpts struct {
	// Pass true if the name of the topic wasn't entered explicitly; for chats with bots only
	IsNameImplicit bool
}

// CreateGroupCallOpts contains optional parameters for CreateGroupCall
type CreateGroupCallOpts struct {
	// Parameters to join the call; pass null to only create call link without joining the call
	JoinParameters *GroupCallJoinParameters
}

// CreateNewBasicGroupChatOpts contains optional parameters for CreateNewBasicGroupChat
type CreateNewBasicGroupChatOpts struct {
	// Identifiers of users to be added to the basic group; may be empty to create a basic group without other members
	UserIds []int64
}

// CreateNewStickerSetOpts contains optional parameters for CreateNewStickerSet
type CreateNewStickerSetOpts struct {
	// Pass true if stickers in the sticker set must be repainted; for custom emoji sticker sets only
	NeedsRepainting bool
	// Source of the sticker set; may be empty if unknown
	Source string
}

// CreateNewSupergroupChatOpts contains optional parameters for CreateNewSupergroupChat
type CreateNewSupergroupChatOpts struct {
	// Pass true to create a supergroup for importing messages using importMessages
	ForImport bool
	// Pass true to create a channel chat; ignored if a forum is created
	IsChannel bool
	// Pass true to create a forum supergroup chat
	IsForum bool
	// Chat location if a location-based supergroup is being created; pass null to create an ordinary supergroup chat
	Location *ChatLocation
}

// CreatePrivateChatOpts contains optional parameters for CreatePrivateChat
type CreatePrivateChatOpts struct {
	// Pass true to create the chat without a network request. In this case all information about the chat except its type, title and photo can be incorrect
	Force bool
}

// CreateRichMessageWithAiOpts contains optional parameters for CreateRichMessageWithAi
type CreateRichMessageWithAiOpts struct {
	// Pass true to add emoji to the text
	AddEmojis bool
}

// CreateSupergroupChatOpts contains optional parameters for CreateSupergroupChat
type CreateSupergroupChatOpts struct {
	// Pass true to create the chat without a network request. In this case all information about the chat except its type, title and photo can be incorrect
	Force bool
}

// CreateTextCompositionStyleOpts contains optional parameters for CreateTextCompositionStyle
type CreateTextCompositionStyleOpts struct {
	// Pass true if the current user must be shown as the creator of the style
	ShowCreator bool
}

// CreateVideoChatOpts contains optional parameters for CreateVideoChat
type CreateVideoChatOpts struct {
	// Pass true to create an RTMP stream instead of an ordinary video chat
	IsRtmpStream bool
}

// DecryptGroupCallDataOpts contains optional parameters for DecryptGroupCallData
type DecryptGroupCallDataOpts struct {
	// Data channel for which data was encrypted; pass null if unknown
	DataChannel GroupCallDataChannel
}

// DeleteAllCallMessagesOpts contains optional parameters for DeleteAllCallMessages
type DeleteAllCallMessagesOpts struct {
	// Pass true to delete the messages for all users
	Revoke bool
}

// DeleteChatBackgroundOpts contains optional parameters for DeleteChatBackground
type DeleteChatBackgroundOpts struct {
	// Pass true to restore previously set background. Can be used only in private and secret chats with non-deleted users if userFullInfo.set_chat_background == true.
	RestorePrevious bool
}

// DeleteChatHistoryOpts contains optional parameters for DeleteChatHistory
type DeleteChatHistoryOpts struct {
	// Pass true to remove the chat from all chat lists
	RemoveFromChatList bool
	// Pass true to delete chat history for all users
	Revoke bool
}

// DeleteChatMessagesByDateOpts contains optional parameters for DeleteChatMessagesByDate
type DeleteChatMessagesByDateOpts struct {
	// Pass true to delete chat messages for all users; private chats only
	Revoke bool
}

// DeleteCommandsOpts contains optional parameters for DeleteCommands
type DeleteCommandsOpts struct {
	// The scope to which the commands are relevant; pass null to delete commands in the default bot command scope
	Scope BotCommandScope
}

// DeleteDefaultBackgroundOpts contains optional parameters for DeleteDefaultBackground
type DeleteDefaultBackgroundOpts struct {
	// Pass true if the background is deleted for a dark theme
	ForDarkTheme bool
}

// DeleteGroupCallMessagesOpts contains optional parameters for DeleteGroupCallMessages
type DeleteGroupCallMessagesOpts struct {
	// Pass true to report the messages as spam
	ReportSpam bool
}

// DeleteGroupCallMessagesBySenderOpts contains optional parameters for DeleteGroupCallMessagesBySender
type DeleteGroupCallMessagesBySenderOpts struct {
	// Pass true to report the messages as spam
	ReportSpam bool
}

// DeleteMessagesOpts contains optional parameters for DeleteMessages
type DeleteMessagesOpts struct {
	// Pass true to delete messages for all chat members. Always true for supergroups, channels and secret chats
	Revoke bool
}

// DiscardCallOpts contains optional parameters for DiscardCall
type DiscardCallOpts struct {
	// Pass true if the user was disconnected
	IsDisconnected bool
	// Pass true if the call was a video call
	IsVideo bool
}

// DownloadFileOpts contains optional parameters for DownloadFile
type DownloadFileOpts struct {
	// Pass true to return response only after the file download has succeeded, has failed, has been canceled, or a new downloadFile request with different offset/limit parameters was sent; pass false to return file state immediately, just after the download has been started
	Synchronous bool
}

// EditBusinessMessageCaptionOpts contains optional parameters for EditBusinessMessageCaption
type EditBusinessMessageCaptionOpts struct {
	// New message content caption; pass null to remove caption; 0-getOption("message_caption_length_max") characters
	Caption *FormattedText
	// The new message reply markup; pass null if none
	ReplyMarkup ReplyMarkup
	// Pass true to show the caption above the media; otherwise, the caption will be shown below the media. May be true only for animation, photo, and video messages
	ShowCaptionAboveMedia bool
}

// EditBusinessMessageChecklistOpts contains optional parameters for EditBusinessMessageChecklist
type EditBusinessMessageChecklistOpts struct {
	// The new message reply markup; pass null if none
	ReplyMarkup ReplyMarkup
}

// EditBusinessMessageLiveLocationOpts contains optional parameters for EditBusinessMessageLiveLocation
type EditBusinessMessageLiveLocationOpts struct {
	// New live location of the message; pass null to stop sharing the live location. If the new live_period isn't set to 0x7FFFFFFF,
	Location *LiveLocation
	// The new message reply markup; pass null if none
	ReplyMarkup ReplyMarkup
}

// EditBusinessMessageMediaOpts contains optional parameters for EditBusinessMessageMedia
type EditBusinessMessageMediaOpts struct {
	// The new message reply markup; pass null if none; for bots only
	ReplyMarkup ReplyMarkup
}

// EditBusinessMessageReplyMarkupOpts contains optional parameters for EditBusinessMessageReplyMarkup
type EditBusinessMessageReplyMarkupOpts struct {
	// The new message reply markup; pass null if none
	ReplyMarkup ReplyMarkup
}

// EditBusinessMessageTextOpts contains optional parameters for EditBusinessMessageText
type EditBusinessMessageTextOpts struct {
	// The new message reply markup; pass null if none
	ReplyMarkup ReplyMarkup
}

// EditCallbackQueryMessageOpts contains optional parameters for EditCallbackQueryMessage
type EditCallbackQueryMessageOpts struct {
	// Pass true if the content of the message must be protected from forwarding and saving
	ProtectContent bool
	// The new message reply markup; pass null if none
	ReplyMarkup ReplyMarkup
}

// EditChatInviteLinkOpts contains optional parameters for EditChatInviteLink
type EditChatInviteLinkOpts struct {
	// Pass true if users joining the chat via the link need to be approved by chat administrators. In this case, member_limit must be 0
	CreatesJoinRequest bool
}

// EditEphemeralMessageOpts contains optional parameters for EditEphemeralMessage
type EditEphemeralMessageOpts struct {
	// New content of the message; pass null to edit only reply markup. Must be one of the following types: inputMessageText, inputMessageAnimation,
	InputMessageContent InputMessageContent
	// The new message reply markup; pass null if none
	ReplyMarkup ReplyMarkup
}

// EditEphemeralMessageCaptionOpts contains optional parameters for EditEphemeralMessageCaption
type EditEphemeralMessageCaptionOpts struct {
	// New message content caption; pass null to remove caption; 0-getOption("message_caption_length_max") characters
	Caption *FormattedText
	// The new message reply markup; pass null if none
	ReplyMarkup ReplyMarkup
	// Pass true to show the caption above the media; otherwise, the caption will be shown below the media. May be true only for animation, photo, and video messages
	ShowCaptionAboveMedia bool
}

// EditForumTopicOpts contains optional parameters for EditForumTopic
type EditForumTopicOpts struct {
	// Pass true to edit the icon of the topic. Icon of the General topic can't be edited
	EditIconCustomEmoji bool
}

// EditInlineMessageCaptionOpts contains optional parameters for EditInlineMessageCaption
type EditInlineMessageCaptionOpts struct {
	// New message content caption; pass null to remove caption; 0-getOption("message_caption_length_max") characters
	Caption *FormattedText
	// The new message reply markup; pass null if none
	ReplyMarkup ReplyMarkup
	// Pass true to show the caption above the media; otherwise, the caption will be shown below the media. May be true only for animation, photo, and video messages
	ShowCaptionAboveMedia bool
}

// EditInlineMessageLiveLocationOpts contains optional parameters for EditInlineMessageLiveLocation
type EditInlineMessageLiveLocationOpts struct {
	// New live location of the message; pass null to stop sharing the live location. If the new live_period isn't set to 0x7FFFFFFF,
	Location *LiveLocation
	// The new message reply markup; pass null if none
	ReplyMarkup ReplyMarkup
}

// EditInlineMessageMediaOpts contains optional parameters for EditInlineMessageMedia
type EditInlineMessageMediaOpts struct {
	// The new message reply markup; pass null if none; for bots only
	ReplyMarkup ReplyMarkup
}

// EditInlineMessageReplyMarkupOpts contains optional parameters for EditInlineMessageReplyMarkup
type EditInlineMessageReplyMarkupOpts struct {
	// The new message reply markup; pass null if none
	ReplyMarkup ReplyMarkup
}

// EditInlineMessageTextOpts contains optional parameters for EditInlineMessageText
type EditInlineMessageTextOpts struct {
	// The new message reply markup; pass null if none
	ReplyMarkup ReplyMarkup
}

// EditMessageCaptionOpts contains optional parameters for EditMessageCaption
type EditMessageCaptionOpts struct {
	// New message content caption; 0-getOption("message_caption_length_max") characters; pass null to remove caption
	Caption *FormattedText
	// The new message reply markup; pass null if none; for bots only
	ReplyMarkup ReplyMarkup
	// Pass true to show the caption above the media; otherwise, the caption will be shown below the media. May be true only for animation, photo, and video messages
	ShowCaptionAboveMedia bool
}

// EditMessageChecklistOpts contains optional parameters for EditMessageChecklist
type EditMessageChecklistOpts struct {
	// The new message reply markup; pass null if none; for bots only
	ReplyMarkup ReplyMarkup
}

// EditMessageLiveLocationOpts contains optional parameters for EditMessageLiveLocation
type EditMessageLiveLocationOpts struct {
	// New live location of the message; pass null to stop sharing the live location. If the new live_period isn't set to 0x7FFFFFFF,
	Location *LiveLocation
	// The new message reply markup; pass null if none; for bots only
	ReplyMarkup ReplyMarkup
}

// EditMessageMediaOpts contains optional parameters for EditMessageMedia
type EditMessageMediaOpts struct {
	// The new message reply markup; pass null if none; for bots only
	ReplyMarkup ReplyMarkup
}

// EditMessageReplyMarkupOpts contains optional parameters for EditMessageReplyMarkup
type EditMessageReplyMarkupOpts struct {
	// The new message reply markup; pass null if none
	ReplyMarkup ReplyMarkup
}

// EditMessageSchedulingStateOpts contains optional parameters for EditMessageSchedulingState
type EditMessageSchedulingStateOpts struct {
	// The new message scheduling state; pass null to send the message immediately. Must be null for messages in the state messageSchedulingStateSendWhenVideoProcessed
	SchedulingState MessageSchedulingState
}

// EditMessageTextOpts contains optional parameters for EditMessageText
type EditMessageTextOpts struct {
	// The new message reply markup; pass null if none; for bots only
	ReplyMarkup ReplyMarkup
}

// EditProxyOpts contains optional parameters for EditProxy
type EditProxyOpts struct {
	// Pass true to immediately enable the proxy
	Enable bool
}

// EditStarSubscriptionOpts contains optional parameters for EditStarSubscription
type EditStarSubscriptionOpts struct {
	// New value of is_canceled
	IsCanceled bool
}

// EditStoryOpts contains optional parameters for EditStory
type EditStoryOpts struct {
	// New clickable rectangle areas to be shown on the story media; pass null to keep the current areas. Areas can't be edited if story content isn't changed
	Areas *InputStoryAreas
	// New story caption; pass null to keep the current caption
	Caption *FormattedText
	// New content of the story; pass null to keep the current content
	Content InputStoryContent
}

// EditTextCompositionStyleOpts contains optional parameters for EditTextCompositionStyle
type EditTextCompositionStyleOpts struct {
	// Pass true if the current user must be shown as the creator of the style
	ShowCreator bool
}

// EditUserStarSubscriptionOpts contains optional parameters for EditUserStarSubscription
type EditUserStarSubscriptionOpts struct {
	// Pass true to cancel the subscription; pass false to allow the user to enable it
	IsCanceled bool
}

// FinishFileGenerationOpts contains optional parameters for FinishFileGeneration
type FinishFileGenerationOpts struct {
	// If passed, the file generation has failed and must be terminated; pass null if the file generation succeeded
	Error *Error
}

// ForwardMessagesOpts contains optional parameters for ForwardMessages
type ForwardMessagesOpts struct {
	// Options to be used to send the messages; pass null to use default options
	Options *MessageSendOptions
	// Pass true to remove media captions of message copies. Ignored if send_copy is false
	RemoveCaption bool
	// Pass true to copy content of the messages without reference to the original sender. Always true if the messages are forwarded to a secret chat or are local.
	SendCopy bool
	// Topic in which the messages will be forwarded; message threads aren't supported; pass null if none
	TopicId MessageTopic
}

// GetAllStickerEmojisOpts contains optional parameters for GetAllStickerEmojis
type GetAllStickerEmojisOpts struct {
	// Pass true if only main emoji for each found sticker must be included in the result
	ReturnOnlyMainEmoji bool
}

// GetBotSimilarBotCountOpts contains optional parameters for GetBotSimilarBotCount
type GetBotSimilarBotCountOpts struct {
	// Pass true to get the number of bots without sending network requests, or -1 if the number of bots is unknown locally
	ReturnLocal bool
}

// GetBusinessFeaturesOpts contains optional parameters for GetBusinessFeatures
type GetBusinessFeaturesOpts struct {
	// Source of the request; pass null if the method is called from settings or some non-standard source
	Source BusinessFeature
}

// GetChatBoostFeaturesOpts contains optional parameters for GetChatBoostFeatures
type GetChatBoostFeaturesOpts struct {
	// Pass true to get the list of features for channels; pass false to get the list of features for supergroups
	IsChannel bool
}

// GetChatBoostLevelFeaturesOpts contains optional parameters for GetChatBoostLevelFeatures
type GetChatBoostLevelFeaturesOpts struct {
	// Pass true to get the list of features for channels; pass false to get the list of features for supergroups
	IsChannel bool
}

// GetChatBoostsOpts contains optional parameters for GetChatBoosts
type GetChatBoostsOpts struct {
	// Pass true to receive only boosts received from gift codes and giveaways created by the chat
	OnlyGiftCodes bool
}

// GetChatEventLogOpts contains optional parameters for GetChatEventLog
type GetChatEventLogOpts struct {
	// The types of events to return; pass null to get chat events of all types
	Filters *ChatEventLogFilters
}

// GetChatHistoryOpts contains optional parameters for GetChatHistory
type GetChatHistoryOpts struct {
	// Pass true to get only messages that are available without sending network requests
	OnlyLocal bool
}

// GetChatInviteLinkMembersOpts contains optional parameters for GetChatInviteLinkMembers
type GetChatInviteLinkMembersOpts struct {
	// A chat member from which to return next chat members; pass null to get results from the beginning
	OffsetMember *ChatInviteLinkMember
	// Pass true if the link is a subscription link and only members with expired subscription must be returned
	OnlyWithExpiredSubscription bool
}

// GetChatInviteLinksOpts contains optional parameters for GetChatInviteLinks
type GetChatInviteLinksOpts struct {
	// Pass true if revoked links need to be returned instead of active or expired
	IsRevoked bool
}

// GetChatJoinRequestsOpts contains optional parameters for GetChatJoinRequests
type GetChatJoinRequestsOpts struct {
	// A chat join request from which to return next requests; pass null to get results from the beginning
	OffsetRequest *ChatJoinRequest
}

// GetChatMessageCalendarOpts contains optional parameters for GetChatMessageCalendar
type GetChatMessageCalendarOpts struct {
	// Pass topic identifier to get the result only in specific topic; pass null to get the result in all topics; forum topics and message threads aren't supported
	TopicId MessageTopic
}

// GetChatMessageCountOpts contains optional parameters for GetChatMessageCount
type GetChatMessageCountOpts struct {
	// Pass true to get the number of messages without sending network requests, or -1 if the number of messages is unknown locally
	ReturnLocal bool
	// Pass topic identifier to get number of messages only in specific topic; pass null to get number of messages in all topics; message threads aren't supported
	TopicId MessageTopic
}

// GetChatMessagePositionOpts contains optional parameters for GetChatMessagePosition
type GetChatMessagePositionOpts struct {
	// Pass topic identifier to get position among messages only in specific topic; pass null to get position among all chat messages; message threads aren't supported
	TopicId MessageTopic
}

// GetChatNotificationSettingsExceptionsOpts contains optional parameters for GetChatNotificationSettingsExceptions
type GetChatNotificationSettingsExceptionsOpts struct {
	// Pass true to include in the response chats with only non-default sound
	CompareSound bool
	// If specified, only chats from the scope will be returned; pass null to return chats from all scopes
	Scope NotificationSettingsScope
}

// GetChatRevenueStatisticsOpts contains optional parameters for GetChatRevenueStatistics
type GetChatRevenueStatisticsOpts struct {
	// Pass true if a dark theme is used by the application
	IsDark bool
}

// GetChatsOpts contains optional parameters for GetChats
type GetChatsOpts struct {
	// The chat list in which to return chats; pass null to get chats from the main chat list
	ChatList ChatList
}

// GetChatSimilarChatCountOpts contains optional parameters for GetChatSimilarChatCount
type GetChatSimilarChatCountOpts struct {
	// Pass true to get the number of chats without sending network requests, or -1 if the number of chats is unknown locally
	ReturnLocal bool
}

// GetChatStatisticsOpts contains optional parameters for GetChatStatistics
type GetChatStatisticsOpts struct {
	// Pass true if a dark theme is used by the application
	IsDark bool
}

// GetChatStoryInteractionsOpts contains optional parameters for GetChatStoryInteractions
type GetChatStoryInteractionsOpts struct {
	// Pass true to get forwards and reposts first, then reactions, then other views; pass false to get interactions sorted just by interaction date
	PreferForwards bool
	// Pass the default heart reaction or a suggested reaction type to receive only interactions with the specified reaction type; pass null to receive all interactions; reactionTypePaid isn't supported
	ReactionType ReactionType
}

// GetCommandsOpts contains optional parameters for GetCommands
type GetCommandsOpts struct {
	// The scope to which the commands are relevant; pass null to get commands in the default bot command scope
	Scope BotCommandScope
}

// GetEmojiCategoriesOpts contains optional parameters for GetEmojiCategories
type GetEmojiCategoriesOpts struct {
	// Type of emoji categories to return; pass null to get default emoji categories
	Type EmojiCategoryType
}

// GetExternalLinkOpts contains optional parameters for GetExternalLink
type GetExternalLinkOpts struct {
	// Pass true if the current user allowed the bot that was returned in getExternalLinkInfo, to send them messages
	AllowWriteAccess bool
}

// GetGramRevenueStatisticsOpts contains optional parameters for GetGramRevenueStatistics
type GetGramRevenueStatisticsOpts struct {
	// Pass true if a dark theme is used by the application
	IsDark bool
}

// GetGroupCallStreamSegmentOpts contains optional parameters for GetGroupCallStreamSegment
type GetGroupCallStreamSegmentOpts struct {
	// Video quality as received from tgcalls; pass null to get the worst available quality
	VideoQuality GroupCallVideoQuality
}

// GetInlineQueryResultsOpts contains optional parameters for GetInlineQueryResults
type GetInlineQueryResultsOpts struct {
	// Location of the user; pass null if unknown or the bot doesn't need user's location
	UserLocation *Location
}

// GetInstalledBackgroundsOpts contains optional parameters for GetInstalledBackgrounds
type GetInstalledBackgroundsOpts struct {
	// Pass true to order returned backgrounds for a dark theme
	ForDarkTheme bool
}

// GetInternalLinkOpts contains optional parameters for GetInternalLink
type GetInternalLinkOpts struct {
	// Pass true to create an HTTPS link (only available for some link types); pass false to create a tg: link
	IsHttp bool
}

// GetKeywordEmojisOpts contains optional parameters for GetKeywordEmojis
type GetKeywordEmojisOpts struct {
	// List of possible IETF language tags of the user's input language; may be empty if unknown
	InputLanguageCodes []string
}

// GetLinkPreviewOpts contains optional parameters for GetLinkPreview
type GetLinkPreviewOpts struct {
	// Options to be used for generation of the link preview; pass null to use default link preview options
	LinkPreviewOptions *LinkPreviewOptions
}

// GetLocalizationTargetInfoOpts contains optional parameters for GetLocalizationTargetInfo
type GetLocalizationTargetInfoOpts struct {
	// Pass true to get only locally available information without sending network requests
	OnlyLocal bool
}

// GetLoginUrlOpts contains optional parameters for GetLoginUrl
type GetLoginUrlOpts struct {
	// Pass true to allow the bot to send messages to the current user. Phone number access can't be requested using the button
	AllowWriteAccess bool
}

// GetManagedBotTokenOpts contains optional parameters for GetManagedBotToken
type GetManagedBotTokenOpts struct {
	// Pass true to revoke the current token and create a new one
	Revoke bool
}

// GetMessageAddedReactionsOpts contains optional parameters for GetMessageAddedReactions
type GetMessageAddedReactionsOpts struct {
	// Type of the reactions to return; pass null to return all added reactions; reactionTypePaid isn't supported
	ReactionType ReactionType
}

// GetMessageEmbeddingCodeOpts contains optional parameters for GetMessageEmbeddingCode
type GetMessageEmbeddingCodeOpts struct {
	// Pass true to return an HTML code for embedding of the whole media album
	ForAlbum bool
}

// GetMessageLinkOpts contains optional parameters for GetMessageLink
type GetMessageLinkOpts struct {
	// Pass true to create a link for the whole media album
	ForAlbum bool
	// Pass true to create a link to the message as a channel post comment, in a message thread, or a forum topic
	InMessageThread bool
}

// GetMessageStatisticsOpts contains optional parameters for GetMessageStatistics
type GetMessageStatisticsOpts struct {
	// Pass true if a dark theme is used by the application
	IsDark bool
}

// GetNetworkStatisticsOpts contains optional parameters for GetNetworkStatistics
type GetNetworkStatisticsOpts struct {
	// Pass true to get statistics only for the current library launch
	OnlyCurrent bool
}

// GetPaymentFormOpts contains optional parameters for GetPaymentForm
type GetPaymentFormOpts struct {
	// Preferred payment form theme; pass null to use the default theme
	Theme *ThemeParameters
}

// GetPollVoteStatisticsOpts contains optional parameters for GetPollVoteStatistics
type GetPollVoteStatisticsOpts struct {
	// Pass true if a dark theme is used by the application
	IsDark bool
}

// GetPremiumFeaturesOpts contains optional parameters for GetPremiumFeatures
type GetPremiumFeaturesOpts struct {
	// Source of the request; pass null if the method is called from some non-standard source
	Source PremiumSource
}

// GetReceivedGiftsOpts contains optional parameters for GetReceivedGifts
type GetReceivedGiftsOpts struct {
	// Pass true to exclude gifts that are just hosted and are not owned by the owner
	ExcludeHosted bool
	// Pass true to exclude gifts that can be purchased limited number of times and can't be upgraded
	ExcludeNonUpgradable bool
	// Pass true to exclude gifts that are saved to the chat's profile page. Always false for gifts received by other users and channel chats without can_post_messages administrator right
	ExcludeSaved bool
	// Pass true to exclude gifts that can be purchased unlimited number of times
	ExcludeUnlimited bool
	// Pass true to exclude gifts that aren't saved to the chat's profile page. Always true for gifts received by other users and channel chats without can_post_messages administrator right
	ExcludeUnsaved bool
	// Pass true to exclude gifts that can be purchased limited number of times and can be upgraded
	ExcludeUpgradable bool
	// Pass true to exclude upgraded gifts
	ExcludeUpgraded bool
	// Pass true to exclude gifts that can't be used in setUpgradedGiftColors
	ExcludeWithoutColors bool
	// Pass true to sort results by gift price instead of send date
	SortByPrice bool
}

// GetRecentStickersOpts contains optional parameters for GetRecentStickers
type GetRecentStickersOpts struct {
	// Pass true to return stickers and masks that were recently attached to photos or video files; pass false to return recently sent stickers
	IsAttached bool
}

// GetRemoteFileOpts contains optional parameters for GetRemoteFile
type GetRemoteFileOpts struct {
	// File type; pass null if unknown
	FileType FileType
}

// GetStarRevenueStatisticsOpts contains optional parameters for GetStarRevenueStatistics
type GetStarRevenueStatisticsOpts struct {
	// Pass true if a dark theme is used by the application
	IsDark bool
}

// GetStarSubscriptionsOpts contains optional parameters for GetStarSubscriptions
type GetStarSubscriptionsOpts struct {
	// Pass true to receive only expiring subscriptions for which there aren't enough Telegram Stars to extend
	OnlyExpiring bool
}

// GetStarTransactionsOpts contains optional parameters for GetStarTransactions
type GetStarTransactionsOpts struct {
	// Direction of the transactions to receive; pass null to get all transactions
	Direction TransactionDirection
	// If non-empty, only transactions related to the Star Subscription will be returned
	SubscriptionId string
}

// GetStickerOutlineOpts contains optional parameters for GetStickerOutline
type GetStickerOutlineOpts struct {
	// Pass true to get the outline scaled for animated emoji
	ForAnimatedEmoji bool
	// Pass true to get the outline scaled for clicked animated emoji message
	ForClickedAnimatedEmojiMessage bool
}

// GetStickerOutlineSvgPathOpts contains optional parameters for GetStickerOutlineSvgPath
type GetStickerOutlineSvgPathOpts struct {
	// Pass true to get the outline scaled for animated emoji
	ForAnimatedEmoji bool
	// Pass true to get the outline scaled for clicked animated emoji message
	ForClickedAnimatedEmojiMessage bool
}

// GetStoryOpts contains optional parameters for GetStory
type GetStoryOpts struct {
	// Pass true to get only locally available information without sending network requests
	OnlyLocal bool
}

// GetStoryInteractionsOpts contains optional parameters for GetStoryInteractions
type GetStoryInteractionsOpts struct {
	// Pass true to get only interactions by contacts; pass false to get all relevant interactions
	OnlyContacts bool
	// Pass true to get forwards and reposts first, then reactions, then other views; pass false to get interactions sorted just by interaction date
	PreferForwards bool
	// Pass true to get interactions with reaction first; pass false to get interactions sorted just by interaction date. Ignored if prefer_forwards == true
	PreferWithReaction bool
	// Query to search for in names, usernames and titles; may be empty to get all relevant interactions
	Query string
}

// GetStoryStatisticsOpts contains optional parameters for GetStoryStatistics
type GetStoryStatisticsOpts struct {
	// Pass true if a dark theme is used by the application
	IsDark bool
}

// GetSupergroupMembersOpts contains optional parameters for GetSupergroupMembers
type GetSupergroupMembersOpts struct {
	// The type of users to return; pass null to use supergroupMembersFilterRecent
	Filter SupergroupMembersFilter
}

// GetTonTransactionsOpts contains optional parameters for GetTonTransactions
type GetTonTransactionsOpts struct {
	// Direction of the transactions to receive; pass null to get all transactions
	Direction TransactionDirection
}

// GetUpgradedGiftVariantsOpts contains optional parameters for GetUpgradedGiftVariants
type GetUpgradedGiftVariantsOpts struct {
	// Pass true to get models that can be obtained by crafting a gift from upgraded gifts
	ReturnCraftModels bool
	// Pass true to get models that can be obtained by upgrading a regular gift
	ReturnUpgradeModels bool
}

// GetVideoChatInviteLinkOpts contains optional parameters for GetVideoChatInviteLink
type GetVideoChatInviteLinkOpts struct {
	// Pass true if the invite link needs to contain an invite hash, passing which to joinVideoChat would allow the invited user to unmute themselves. Requires groupCall.can_be_managed right
	CanSelfUnmute bool
}

// GetWebAppLinkUrlOpts contains optional parameters for GetWebAppLinkUrl
type GetWebAppLinkUrlOpts struct {
	// Pass true if the current user allowed the bot to send them messages
	AllowWriteAccess bool
}

// GetWebPageInstantViewOpts contains optional parameters for GetWebPageInstantView
type GetWebPageInstantViewOpts struct {
	// Pass true to get only locally available information without sending network requests
	OnlyLocal bool
}

// InviteGroupCallParticipantOpts contains optional parameters for InviteGroupCallParticipant
type InviteGroupCallParticipantOpts struct {
	// Pass true if the group call is a video call
	IsVideo bool
}

// JoinVideoChatOpts contains optional parameters for JoinVideoChat
type JoinVideoChatOpts struct {
	// Identifier of a group call participant, which will be used to join the call; pass null to join as self
	ParticipantId MessageSender
}

// LoadChatsOpts contains optional parameters for LoadChats
type LoadChatsOpts struct {
	// The chat list in which to load chats; pass null to load chats from the main chat list
	ChatList ChatList
}

// OpenWebAppOpts contains optional parameters for OpenWebApp
type OpenWebAppOpts struct {
	// Information about the message or story to be replied in the message sent by the Web App; pass null if none
	ReplyTo InputMessageReplyTo
	// Topic in which the message will be sent; pass null if none
	TopicId MessageTopic
}

// OptimizeStorageOpts contains optional parameters for OptimizeStorage
type OptimizeStorageOpts struct {
	// If non-empty, only files from the given chats are considered. Use 0 as chat identifier to delete files not belonging to any chat (e.g., profile photos)
	ChatIds []int64
	// If non-empty, files from the given chats are excluded. Use 0 as chat identifier to exclude all files not belonging to any chat (e.g., profile photos)
	ExcludeChatIds []int64
	// If non-empty, only files with the given types are considered. By default, all types except thumbnails, profile photos, stickers and wallpapers are deleted
	FileTypes []FileType
	// Pass true if statistics about the files that were deleted must be returned instead of the whole storage usage statistics. Affects only returned statistics
	ReturnDeletedFileStatistics bool
}

// PinChatMessageOpts contains optional parameters for PinChatMessage
type PinChatMessageOpts struct {
	// Pass true to disable notification about the pinned message. Notifications are always disabled in channels and private chats
	DisableNotification bool
	// Pass true to pin the message only for self; private chats only
	OnlyForSelf bool
}

// PingProxyOpts contains optional parameters for PingProxy
type PingProxyOpts struct {
	// The proxy to test; pass null to ping a Telegram server without a proxy
	Proxy *Proxy
}

// PlaceGiftAuctionBidOpts contains optional parameters for PlaceGiftAuctionBid
type PlaceGiftAuctionBidOpts struct {
	// Pass true to show gift text and sender only to the gift receiver; otherwise, everyone will be able to see them
	IsPrivate bool
}

// PostStoryOpts contains optional parameters for PostStory
type PostStoryOpts struct {
	// Clickable rectangle areas to be shown on the story media; pass null if none
	Areas *InputStoryAreas
	// Story caption; pass null to use an empty caption; 0-getOption("story_caption_length_max") characters; can have entities only if getOption("can_use_text_entities_in_story_caption")
	Caption *FormattedText
	// Full identifier of the original story, which content was used to create the story; pass null if the story isn't repost of another story
	FromStoryFullId *StoryFullId
	// Pass true to keep the story accessible after expiration
	IsPostedToChatPage bool
	// Pass true if the content of the story must be protected from forwarding and screenshotting
	ProtectContent bool
}

// PreliminaryUploadFileOpts contains optional parameters for PreliminaryUploadFile
type PreliminaryUploadFileOpts struct {
	// File type; pass null if unknown
	FileType FileType
}

// ProcessChatHasProtectedContentDisableRequestOpts contains optional parameters for ProcessChatHasProtectedContentDisableRequest
type ProcessChatHasProtectedContentDisableRequestOpts struct {
	// Pass true to approve the request; pass false to reject the request
	Approve bool
}

// ProcessChatJoinRequestOpts contains optional parameters for ProcessChatJoinRequest
type ProcessChatJoinRequestOpts struct {
	// Pass true to approve the request; pass false to decline it
	Approve bool
}

// ProcessChatJoinRequestsOpts contains optional parameters for ProcessChatJoinRequests
type ProcessChatJoinRequestsOpts struct {
	// Pass true to approve all requests; pass false to decline them
	Approve bool
}

// ProcessGiftPurchaseOfferOpts contains optional parameters for ProcessGiftPurchaseOffer
type ProcessGiftPurchaseOfferOpts struct {
	// Pass true to accept the request; pass false to reject it
	Accept bool
}

// RateSpeechRecognitionOpts contains optional parameters for RateSpeechRecognition
type RateSpeechRecognitionOpts struct {
	// Pass true if the speech recognition is good
	IsGood bool
}

// RecoverAuthenticationPasswordOpts contains optional parameters for RecoverAuthenticationPassword
type RecoverAuthenticationPasswordOpts struct {
	// New password hint; may be empty
	NewHint string
	// New 2-step verification password of the user; may be empty to remove the password
	NewPassword string
}

// RecoverPasswordOpts contains optional parameters for RecoverPassword
type RecoverPasswordOpts struct {
	// New password hint; may be empty
	NewHint string
	// New 2-step verification password of the user; may be empty to remove the password
	NewPassword string
}

// RegisterUserOpts contains optional parameters for RegisterUser
type RegisterUserOpts struct {
	// Pass true to disable notification about the current user joining Telegram for other users that added them to contact list
	DisableNotification bool
}

// RemoveAllFilesFromDownloadsOpts contains optional parameters for RemoveAllFilesFromDownloads
type RemoveAllFilesFromDownloadsOpts struct {
	// Pass true to delete the file from the TDLib file cache
	DeleteFromCache bool
	// Pass true to remove only active downloads, including paused
	OnlyActive bool
	// Pass true to remove only completed downloads
	OnlyCompleted bool
}

// RemoveFileFromDownloadsOpts contains optional parameters for RemoveFileFromDownloads
type RemoveFileFromDownloadsOpts struct {
	// Pass true to delete the file from the TDLib file cache
	DeleteFromCache bool
}

// RemoveRecentStickerOpts contains optional parameters for RemoveRecentSticker
type RemoveRecentStickerOpts struct {
	// Pass true to remove the sticker from the list of stickers recently attached to photo or video files; pass false to remove the sticker from the list of recently sent stickers
	IsAttached bool
}

// ResendAuthenticationCodeOpts contains optional parameters for ResendAuthenticationCode
type ResendAuthenticationCodeOpts struct {
	// Reason of code resending; pass null if unknown
	Reason ResendCodeReason
}

// ResendMessagesOpts contains optional parameters for ResendMessages
type ResendMessagesOpts struct {
	// New manually chosen quote from the message to be replied; pass null if none. Ignored if more than one message is re-sent, or if messageSendingStateFailed.need_another_reply_quote == false
	Quote *InputTextQuote
}

// ResendPhoneNumberCodeOpts contains optional parameters for ResendPhoneNumberCode
type ResendPhoneNumberCodeOpts struct {
	// Reason of code resending; pass null if unknown
	Reason ResendCodeReason
}

// SearchCallMessagesOpts contains optional parameters for SearchCallMessages
type SearchCallMessagesOpts struct {
	// Pass true to search only for messages with missed/declined calls
	OnlyMissed bool
}

// SearchChatMembersOpts contains optional parameters for SearchChatMembers
type SearchChatMembersOpts struct {
	// The type of users to search for; pass null to search among all chat members
	Filter ChatMembersFilter
}

// SearchChatMessagesOpts contains optional parameters for SearchChatMessages
type SearchChatMessagesOpts struct {
	// Additional filter for messages to search; pass null to search for all messages
	Filter SearchMessagesFilter
	// Identifier of the sender of messages to search for; pass null to search for messages from any sender. Not supported in secret chats
	SenderId MessageSender
	// Pass topic identifier to search messages only in specific topic; pass null to search for messages in all topics
	TopicId MessageTopic
}

// SearchChatsOpts contains optional parameters for SearchChats
type SearchChatsOpts struct {
	// Additional filter for type of the chats to be returned; pass null to search for chats of all types
	TypeFilter SearchChatTypeFilter
}

// SearchChatsOnServerOpts contains optional parameters for SearchChatsOnServer
type SearchChatsOnServerOpts struct {
	// Additional filter for type of the chats to be returned; pass null to search for chats of all types
	TypeFilter SearchChatTypeFilter
}

// SearchContactsOpts contains optional parameters for SearchContacts
type SearchContactsOpts struct {
	// Query to search for; may be empty to return all contacts
	Query string
}

// SearchEmojisOpts contains optional parameters for SearchEmojis
type SearchEmojisOpts struct {
	// List of possible IETF language tags of the user's input language; may be empty if unknown
	InputLanguageCodes []string
}

// SearchFileDownloadsOpts contains optional parameters for SearchFileDownloads
type SearchFileDownloadsOpts struct {
	// Pass true to search only for active downloads, including paused
	OnlyActive bool
	// Pass true to search only for completed downloads
	OnlyCompleted bool
	// Query to search for; may be empty to return all downloaded files
	Query string
}

// SearchGiftsForResaleOpts contains optional parameters for SearchGiftsForResale
type SearchGiftsForResaleOpts struct {
	// Pass true to get only gifts suitable for crafting
	ForCrafting bool
	// Pass true to get only gifts that can be bought using Telegram Stars
	ForStars bool
}

// SearchMessagesOpts contains optional parameters for SearchMessages
type SearchMessagesOpts struct {
	// Chat list in which to search messages; pass null to search in all chats regardless of their chat list. Only Main and Archive chat lists are supported
	ChatList ChatList
	// Additional filter for type of the chat of the searched messages; pass null to search for messages in all chats
	ChatTypeFilter SearchMessagesChatTypeFilter
	// Additional filter for messages to search; pass null to search for all messages. Filters searchMessagesFilterMention, searchMessagesFilterUnreadMention, searchMessagesFilterUnreadReaction,
	Filter SearchMessagesFilter
}

// SearchPublicChatsOpts contains optional parameters for SearchPublicChats
type SearchPublicChatsOpts struct {
	// Additional filter for type of the chats to be returned; pass null to search for chats of all types
	TypeFilter SearchChatTypeFilter
}

// SearchRecentlyFoundChatsOpts contains optional parameters for SearchRecentlyFoundChats
type SearchRecentlyFoundChatsOpts struct {
	// Additional filter for type of the chats to be returned; pass null to search for chats of all types
	TypeFilter SearchChatTypeFilter
}

// SearchSavedMessagesOpts contains optional parameters for SearchSavedMessages
type SearchSavedMessagesOpts struct {
	// Tag to search for; pass null to return all suitable messages
	Tag ReactionType
}

// SearchSecretMessagesOpts contains optional parameters for SearchSecretMessages
type SearchSecretMessagesOpts struct {
	// Additional filter for messages to search; pass null to search for all messages
	Filter SearchMessagesFilter
}

// SearchStickersOpts contains optional parameters for SearchStickers
type SearchStickersOpts struct {
	// List of possible IETF language tags of the user's input language; may be empty if unknown
	InputLanguageCodes []string
	// Query to search for; may be empty to search for emoji only
	Query string
}

// SearchStickerSetOpts contains optional parameters for SearchStickerSet
type SearchStickerSetOpts struct {
	// Pass true to ignore local cache of sticker sets and always send a network request
	IgnoreCache bool
}

// SearchStringsByPrefixOpts contains optional parameters for SearchStringsByPrefix
type SearchStringsByPrefixOpts struct {
	// Pass true to receive no results for an empty query
	ReturnNoneForEmptyQuery bool
}

// SearchUserByPhoneNumberOpts contains optional parameters for SearchUserByPhoneNumber
type SearchUserByPhoneNumberOpts struct {
	// Pass true to get only locally available information without sending network requests
	OnlyLocal bool
}

// SendBusinessMessageOpts contains optional parameters for SendBusinessMessage
type SendBusinessMessageOpts struct {
	// Pass true to disable notification for the message
	DisableNotification bool
	// Pass true if the content of the message must be protected from forwarding and saving
	ProtectContent bool
	// Markup for replying to the message; pass null if none
	ReplyMarkup ReplyMarkup
	// Information about the message to be replied; pass null if none
	ReplyTo InputMessageReplyTo
}

// SendBusinessMessageAlbumOpts contains optional parameters for SendBusinessMessageAlbum
type SendBusinessMessageAlbumOpts struct {
	// Pass true to disable notification for the message
	DisableNotification bool
	// Pass true if the content of the message must be protected from forwarding and saving
	ProtectContent bool
	// Information about the message to be replied; pass null if none
	ReplyTo InputMessageReplyTo
}

// SendChatActionOpts contains optional parameters for SendChatAction
type SendChatActionOpts struct {
	// The action description; pass null to cancel the currently active action
	Action ChatAction
	// Identifier of the topic in which the action is performed; pass null if none
	TopicId MessageTopic
}

// SendEphemeralMessageOpts contains optional parameters for SendEphemeralMessage
type SendEphemeralMessageOpts struct {
	// Pass true to get a fake message instead of actually sending them
	OnlyPreview bool
	// Pass true if the content of the message must be protected from forwarding and saving; for bots only
	ProtectContent bool
	// Pass true if the ephemeral message must replace the message from which the callback query originated; for bots only
	ReplaceCallbackQueryMessage bool
	// Markup for replying to the message; pass null if none; for bots only
	ReplyMarkup ReplyMarkup
	// Information about the message to be replied; pass null if none. The message can be an incoming ephemeral message
	ReplyTo InputMessageReplyTo
	// Topic in which the message will be sent; pass null if none
	TopicId MessageTopic
}

// SendGiftOpts contains optional parameters for SendGift
type SendGiftOpts struct {
	// Pass true to show gift text and sender only to the gift receiver; otherwise, everyone will be able to see them
	IsPrivate bool
	// Pass true to additionally pay for the gift upgrade and allow the receiver to upgrade it for free
	PayForUpgrade bool
}

// SendInlineQueryResultMessageOpts contains optional parameters for SendInlineQueryResultMessage
type SendInlineQueryResultMessageOpts struct {
	// Pass true to hide the bot, via which the message is sent. Can be used only for bots getOption("animation_search_bot_username"), getOption("photo_search_bot_username"), and getOption("venue_search_bot_username")
	HideViaBot bool
	// Options to be used to send the message; pass null to use default options
	Options *MessageSendOptions
	// Information about the message or story to be replied; pass null if none
	ReplyTo InputMessageReplyTo
	// Topic in which the message will be sent; pass null if none
	TopicId MessageTopic
}

// SendMessageOpts contains optional parameters for SendMessage
type SendMessageOpts struct {
	// Options to be used to send the message; pass null to use default options
	Options *MessageSendOptions
	// Markup for replying to the message; pass null if none; for bots only
	ReplyMarkup ReplyMarkup
	// Information about the message or story to be replied; pass null if none
	ReplyTo InputMessageReplyTo
	// Topic in which the message will be sent; pass null if none
	TopicId MessageTopic
}

// SendMessageAlbumOpts contains optional parameters for SendMessageAlbum
type SendMessageAlbumOpts struct {
	// Options to be used to send the messages; pass null to use default options
	Options *MessageSendOptions
	// Information about the message or story to be replied; pass null if none
	ReplyTo InputMessageReplyTo
	// Topic in which the messages will be sent; pass null if none
	TopicId MessageTopic
}

// SendPaymentFormOpts contains optional parameters for SendPaymentForm
type SendPaymentFormOpts struct {
	// The credentials chosen by user for payment; pass null for a payment in Telegram Stars
	Credentials InputCredentials
}

// SendPhoneNumberCodeOpts contains optional parameters for SendPhoneNumberCode
type SendPhoneNumberCodeOpts struct {
	// Settings for the authentication of the user's phone number; pass null to use default settings
	Settings *PhoneNumberAuthenticationSettings
}

// SendResoldGiftOpts contains optional parameters for SendResoldGift
type SendResoldGiftOpts struct {
	// Pass true to show gift text and sender only to the gift receiver; otherwise, everyone will be able to see them
	IsPrivate bool
}

// SendRichMessageDraftOpts contains optional parameters for SendRichMessageDraft
type SendRichMessageDraftOpts struct {
	// Pass true to show the user a button to stop further drafts
	CanStop bool
	// Pass true to keep the current draft when the user stops further generation
	KeepOnStop bool
}

// SendTextMessageDraftOpts contains optional parameters for SendTextMessageDraft
type SendTextMessageDraftOpts struct {
	// Pass true to show the user a button to stop further drafts
	CanStop bool
	// Pass true to keep the current draft when the user stops further generation
	KeepOnStop bool
	// Draft text of the message; pass null to show a "Thinking..." placeholder
	Text *FormattedText
}

// SetAuthenticationPhoneNumberOpts contains optional parameters for SetAuthenticationPhoneNumber
type SetAuthenticationPhoneNumberOpts struct {
	// Settings for the authentication of the user's phone number; pass null to use default settings
	Settings *PhoneNumberAuthenticationSettings
}

// SetAuthenticationPremiumPurchaseTransactionOpts contains optional parameters for SetAuthenticationPremiumPurchaseTransaction
type SetAuthenticationPremiumPurchaseTransactionOpts struct {
	// Pass true if this is a restore of a Telegram Premium purchase; only for App Store
	IsRestore bool
}

// SetAutosaveSettingsOpts contains optional parameters for SetAutosaveSettings
type SetAutosaveSettingsOpts struct {
	// New autosave settings for the scope; pass null to set autosave settings to default
	Settings *ScopeAutosaveSettings
}

// SetBirthdateOpts contains optional parameters for SetBirthdate
type SetBirthdateOpts struct {
	// The new value of the current user's birthdate; pass null to remove the birthdate
	Birthdate *Birthdate
}

// SetBotProfilePhotoOpts contains optional parameters for SetBotProfilePhoto
type SetBotProfilePhotoOpts struct {
	// Profile photo to set; pass null to delete the chat photo
	Photo InputChatPhoto
}

// SetBusinessAccountProfilePhotoOpts contains optional parameters for SetBusinessAccountProfilePhoto
type SetBusinessAccountProfilePhotoOpts struct {
	// Pass true to set the public photo, which will be visible even if the main photo is hidden by privacy settings
	IsPublic bool
	// Profile photo to set; pass null to remove the photo
	Photo InputChatPhoto
}

// SetBusinessAwayMessageSettingsOpts contains optional parameters for SetBusinessAwayMessageSettings
type SetBusinessAwayMessageSettingsOpts struct {
	// The new settings for the away message of the business; pass null to disable the away message
	AwayMessageSettings *BusinessAwayMessageSettings
}

// SetBusinessGreetingMessageSettingsOpts contains optional parameters for SetBusinessGreetingMessageSettings
type SetBusinessGreetingMessageSettingsOpts struct {
	// The new settings for the greeting message of the business; pass null to disable the greeting message
	GreetingMessageSettings *BusinessGreetingMessageSettings
}

// SetBusinessLocationOpts contains optional parameters for SetBusinessLocation
type SetBusinessLocationOpts struct {
	// The new location of the business; pass null to remove the location
	Location *BusinessLocation
}

// SetBusinessMessageIsPinnedOpts contains optional parameters for SetBusinessMessageIsPinned
type SetBusinessMessageIsPinnedOpts struct {
	// Pass true to pin the message, pass false to unpin it
	IsPinned bool
}

// SetBusinessOpeningHoursOpts contains optional parameters for SetBusinessOpeningHours
type SetBusinessOpeningHoursOpts struct {
	// The new opening hours of the business; pass null to remove the opening hours; up to 28 time intervals can be specified
	OpeningHours *BusinessOpeningHours
}

// SetBusinessStartPageOpts contains optional parameters for SetBusinessStartPage
type SetBusinessStartPageOpts struct {
	// The new start page of the business; pass null to remove custom start page
	StartPage *InputBusinessStartPage
}

// SetChatAffiliateProgramOpts contains optional parameters for SetChatAffiliateProgram
type SetChatAffiliateProgramOpts struct {
	// Parameters of the affiliate program; pass null to close the currently active program. If there is an active program, then commission and program duration can only be increased.
	Parameters *AffiliateProgramParameters
}

// SetChatBackgroundOpts contains optional parameters for SetChatBackground
type SetChatBackgroundOpts struct {
	// The input background to use; pass null to create a new filled or chat theme background
	Background InputBackground
	// Pass true to set background only for self; pass false to set background for all chat users. Always false for backgrounds set in boosted chats. Background can be set for both users only by Telegram Premium users and if set background isn't of the type inputBackgroundPrevious
	OnlyForSelf bool
	// Background type; pass null to use default background type for the chosen background; backgroundTypeChatTheme isn't supported for private and secret chats.
	Type BackgroundType
}

// SetChatDirectMessagesGroupOpts contains optional parameters for SetChatDirectMessagesGroup
type SetChatDirectMessagesGroupOpts struct {
	// Pass true if the direct messages group is enabled for the channel chat; pass false otherwise
	IsEnabled bool
}

// SetChatDraftMessageOpts contains optional parameters for SetChatDraftMessage
type SetChatDraftMessageOpts struct {
	// New draft message; pass null to remove the draft
	DraftMessage *DraftMessage
	// Topic in which the draft will be changed; pass null to change the draft for the chat itself
	TopicId MessageTopic
}

// SetChatEmojiStatusOpts contains optional parameters for SetChatEmojiStatus
type SetChatEmojiStatusOpts struct {
	// New emoji status; pass null to remove emoji status
	EmojiStatus *EmojiStatus
}

// SetChatPhotoOpts contains optional parameters for SetChatPhoto
type SetChatPhotoOpts struct {
	// New chat photo; pass null to delete the chat photo
	Photo InputChatPhoto
}

// SetChatThemeOpts contains optional parameters for SetChatTheme
type SetChatThemeOpts struct {
	// New chat theme; pass null to return the default theme
	Theme InputChatTheme
}

// SetCommandsOpts contains optional parameters for SetCommands
type SetCommandsOpts struct {
	// The scope to which the commands are relevant; pass null to change commands in the default bot command scope
	Scope BotCommandScope
}

// SetDefaultBackgroundOpts contains optional parameters for SetDefaultBackground
type SetDefaultBackgroundOpts struct {
	// The input background to use; pass null to create a new filled background
	Background InputBackground
	// Pass true if the background is set for a dark theme
	ForDarkTheme bool
	// Background type; pass null to use the default type of the remote background; backgroundTypeChatTheme isn't supported
	Type BackgroundType
}

// SetDefaultChannelAdministratorRightsOpts contains optional parameters for SetDefaultChannelAdministratorRights
type SetDefaultChannelAdministratorRightsOpts struct {
	// Default administrator rights for adding the bot to channels; pass null to remove default rights
	DefaultChannelAdministratorRights *ChatAdministratorRights
}

// SetDefaultGroupAdministratorRightsOpts contains optional parameters for SetDefaultGroupAdministratorRights
type SetDefaultGroupAdministratorRightsOpts struct {
	// Default administrator rights for adding the bot to basic group and supergroup chats; pass null to remove default rights
	DefaultGroupAdministratorRights *ChatAdministratorRights
}

// SetDirectMessagesChatTopicIsMarkedAsUnreadOpts contains optional parameters for SetDirectMessagesChatTopicIsMarkedAsUnread
type SetDirectMessagesChatTopicIsMarkedAsUnreadOpts struct {
	// New value of is_marked_as_unread
	IsMarkedAsUnread bool
}

// SetEmojiStatusOpts contains optional parameters for SetEmojiStatus
type SetEmojiStatusOpts struct {
	// New emoji status; pass null to switch to the default badge
	EmojiStatus *EmojiStatus
}

// SetGameScoreOpts contains optional parameters for SetGameScore
type SetGameScoreOpts struct {
	// Pass true to edit the game message to include the current scoreboard
	EditMessage bool
	// Pass true to update the score even if it decreases. If the score is 0, the user will be deleted from the high score table
	Force bool
}

// SetGiftResalePriceOpts contains optional parameters for SetGiftResalePrice
type SetGiftResalePriceOpts struct {
	// The new price for the unique gift; pass null to disallow gift resale. The current user will receive
	Price GiftResalePrice
}

// SetGroupCallParticipantIsSpeakingOpts contains optional parameters for SetGroupCallParticipantIsSpeaking
type SetGroupCallParticipantIsSpeakingOpts struct {
	// Pass true if the user is speaking
	IsSpeaking bool
}

// SetInlineGameScoreOpts contains optional parameters for SetInlineGameScore
type SetInlineGameScoreOpts struct {
	// Pass true to edit the game message to include the current scoreboard
	EditMessage bool
	// Pass true to update the score even if it decreases. If the score is 0, the user will be deleted from the high score table
	Force bool
}

// SetMessageFactCheckOpts contains optional parameters for SetMessageFactCheck
type SetMessageFactCheckOpts struct {
	// New text of the fact-check; 0-getOption("fact_check_length_max") characters; pass null to remove it. Only Bold, Italic, and TextUrl entities with https://t.me/ links are supported
	Text *FormattedText
}

// SetMessageReactionsOpts contains optional parameters for SetMessageReactions
type SetMessageReactionsOpts struct {
	// Pass true if the reactions are added with a big animation
	IsBig bool
}

// SetMessageSenderBlockListOpts contains optional parameters for SetMessageSenderBlockList
type SetMessageSenderBlockListOpts struct {
	// New block list for the message sender; pass null to unblock the message sender
	BlockList BlockList
}

// SetNetworkTypeOpts contains optional parameters for SetNetworkType
type SetNetworkTypeOpts struct {
	// The new network type; pass null to set network type to networkTypeOther
	Type NetworkType
}

// SetOptionOpts contains optional parameters for SetOption
type SetOptionOpts struct {
	// The new value of the option; pass null to reset option value to a default value
	Value OptionValue
}

// SetPasswordOpts contains optional parameters for SetPassword
type SetPasswordOpts struct {
	// New password hint; may be empty
	NewHint string
	// New 2-step verification password of the user; may be empty to remove the password
	NewPassword string
	// New recovery email address; may be empty
	NewRecoveryEmailAddress string
	// Pass true to change also the recovery email address
	SetRecoveryEmailAddress bool
}

// SetProfilePhotoOpts contains optional parameters for SetProfilePhoto
type SetProfilePhotoOpts struct {
	// Pass true to set the public photo, which will be visible even if the main photo is hidden by privacy settings
	IsPublic bool
}

// SetStickerMaskPositionOpts contains optional parameters for SetStickerMaskPosition
type SetStickerMaskPositionOpts struct {
	// Position where the mask is placed; pass null to remove mask position
	MaskPosition *MaskPosition
}

// SetStickerSetThumbnailOpts contains optional parameters for SetStickerSetThumbnail
type SetStickerSetThumbnailOpts struct {
	// Format of the thumbnail; pass null if thumbnail is removed
	Format StickerFormat
	// Thumbnail to set; pass null to remove the sticker set thumbnail
	Thumbnail InputFile
}

// SetStoryReactionOpts contains optional parameters for SetStoryReaction
type SetStoryReactionOpts struct {
	// Type of the reaction to set; pass null to remove the reaction. Custom emoji reactions can be used only by Telegram Premium users. Paid reactions can't be set
	ReactionType ReactionType
	// Pass true if the reaction needs to be added to recent reactions
	UpdateRecentReactions bool
}

// SetTdlibParametersOpts contains optional parameters for SetTdlibParameters
type SetTdlibParametersOpts struct {
	// Pass true to keep cache of users, basic groups, supergroups, channels and secret chats between restarts. Implies use_file_database
	UseChatInfoDatabase bool
	// Pass true to keep information about downloaded and uploaded files between application restarts
	UseFileDatabase bool
	// Pass true to keep cache of chats and messages between restarts. Implies use_chat_info_database
	UseMessageDatabase bool
	// Pass true to enable support for secret chats
	UseSecretChats bool
	// Pass true to use Telegram test environment instead of the production environment
	UseTestDc bool
}

// SetUserEmojiStatusOpts contains optional parameters for SetUserEmojiStatus
type SetUserEmojiStatusOpts struct {
	// New emoji status; pass null to switch to the default badge
	EmojiStatus *EmojiStatus
}

// SetUserPersonalProfilePhotoOpts contains optional parameters for SetUserPersonalProfilePhoto
type SetUserPersonalProfilePhotoOpts struct {
	// Profile photo to set; pass null to delete the photo; inputChatPhotoPrevious isn't supported in this function
	Photo InputChatPhoto
}

// ShareChatWithBotOpts contains optional parameters for ShareChatWithBot
type ShareChatWithBotOpts struct {
	// Pass true to check that the chat can be shared by the button instead of actually sharing it. Doesn't check bot_is_member and bot_administrator_rights restrictions.
	OnlyCheck bool
}

// ShareUsersWithBotOpts contains optional parameters for ShareUsersWithBot
type ShareUsersWithBotOpts struct {
	// Pass true to check that the users can be shared by the button instead of actually sharing them
	OnlyCheck bool
}

// StartGroupCallRecordingOpts contains optional parameters for StartGroupCallRecording
type StartGroupCallRecordingOpts struct {
	// Pass true to record a video file instead of an audio file
	RecordVideo bool
	// Pass true to use portrait orientation for video instead of landscape one
	UsePortraitOrientation bool
}

// StartLiveStoryOpts contains optional parameters for StartLiveStory
type StartLiveStoryOpts struct {
	// Pass true to allow viewers of the story to send messages
	EnableMessages bool
	// Pass true to create an RTMP stream instead of an ordinary group call
	IsRtmpStream bool
	// Pass true if the content of the story must be protected from screenshotting
	ProtectContent bool
}

// StopBusinessPollOpts contains optional parameters for StopBusinessPoll
type StopBusinessPollOpts struct {
	// The new message reply markup; pass null if none
	ReplyMarkup ReplyMarkup
}

// StopPendingMessageOpts contains optional parameters for StopPendingMessage
type StopPendingMessageOpts struct {
	// Identifier of the topic in which the action is performed; pass null if none
	TopicId MessageTopic
}

// StopPollOpts contains optional parameters for StopPoll
type StopPollOpts struct {
	// The new message reply markup; pass null if none; for bots only
	ReplyMarkup ReplyMarkup
}

// ToggleAllDownloadsArePausedOpts contains optional parameters for ToggleAllDownloadsArePaused
type ToggleAllDownloadsArePausedOpts struct {
	// Pass true to pause all downloads; pass false to unpause them
	ArePaused bool
}

// ToggleBotCanManageEmojiStatusOpts contains optional parameters for ToggleBotCanManageEmojiStatus
type ToggleBotCanManageEmojiStatusOpts struct {
	// Pass true if the bot is allowed to change emoji status of the user; pass false otherwise
	CanManageEmojiStatus bool
}

// ToggleBotIsAddedToAttachmentMenuOpts contains optional parameters for ToggleBotIsAddedToAttachmentMenu
type ToggleBotIsAddedToAttachmentMenuOpts struct {
	// Pass true if the current user allowed the bot to send them messages. Ignored if is_added is false
	AllowWriteAccess bool
	// Pass true to add the bot to attachment menu; pass false to remove the bot from attachment menu
	IsAdded bool
}

// ToggleBotUsernameIsActiveOpts contains optional parameters for ToggleBotUsernameIsActive
type ToggleBotUsernameIsActiveOpts struct {
	// Pass true to activate the username; pass false to disable it
	IsActive bool
}

// ToggleBusinessConnectedBotChatIsPausedOpts contains optional parameters for ToggleBusinessConnectedBotChatIsPaused
type ToggleBusinessConnectedBotChatIsPausedOpts struct {
	// Pass true to pause the connected bot in the chat; pass false to resume the bot
	IsPaused bool
}

// ToggleChatDefaultDisableNotificationOpts contains optional parameters for ToggleChatDefaultDisableNotification
type ToggleChatDefaultDisableNotificationOpts struct {
	// New value of default_disable_notification
	DefaultDisableNotification bool
}

// ToggleChatFolderTagsOpts contains optional parameters for ToggleChatFolderTags
type ToggleChatFolderTagsOpts struct {
	// Pass true to enable folder tags; pass false to disable them
	AreTagsEnabled bool
}

// ToggleChatGiftNotificationsOpts contains optional parameters for ToggleChatGiftNotifications
type ToggleChatGiftNotificationsOpts struct {
	// Pass true to enable notifications about new gifts owned by the channel chat; pass false to disable the notifications
	AreEnabled bool
}

// ToggleChatHasProtectedContentOpts contains optional parameters for ToggleChatHasProtectedContent
type ToggleChatHasProtectedContentOpts struct {
	// New value of has_protected_content
	HasProtectedContent bool
}

// ToggleChatIsMarkedAsUnreadOpts contains optional parameters for ToggleChatIsMarkedAsUnread
type ToggleChatIsMarkedAsUnreadOpts struct {
	// New value of is_marked_as_unread
	IsMarkedAsUnread bool
}

// ToggleChatIsPinnedOpts contains optional parameters for ToggleChatIsPinned
type ToggleChatIsPinnedOpts struct {
	// Pass true to pin the chat; pass false to unpin it
	IsPinned bool
}

// ToggleChatIsTranslatableOpts contains optional parameters for ToggleChatIsTranslatable
type ToggleChatIsTranslatableOpts struct {
	// New value of is_translatable
	IsTranslatable bool
}

// ToggleChatViewAsTopicsOpts contains optional parameters for ToggleChatViewAsTopics
type ToggleChatViewAsTopicsOpts struct {
	// New value of view_as_topics
	ViewAsTopics bool
}

// ToggleDirectMessagesChatTopicCanSendUnpaidMessagesOpts contains optional parameters for ToggleDirectMessagesChatTopicCanSendUnpaidMessages
type ToggleDirectMessagesChatTopicCanSendUnpaidMessagesOpts struct {
	// Pass true to allow unpaid messages; pass false to disallow unpaid messages
	CanSendUnpaidMessages bool
	// Pass true to refund the user previously paid messages
	RefundPayments bool
}

// ToggleDownloadIsPausedOpts contains optional parameters for ToggleDownloadIsPaused
type ToggleDownloadIsPausedOpts struct {
	// Pass true if the download is paused
	IsPaused bool
}

// ToggleForumTopicIsClosedOpts contains optional parameters for ToggleForumTopicIsClosed
type ToggleForumTopicIsClosedOpts struct {
	// Pass true to close the topic; pass false to reopen it
	IsClosed bool
}

// ToggleForumTopicIsPinnedOpts contains optional parameters for ToggleForumTopicIsPinned
type ToggleForumTopicIsPinnedOpts struct {
	// Pass true to pin the topic; pass false to unpin it
	IsPinned bool
}

// ToggleGeneralForumTopicIsHiddenOpts contains optional parameters for ToggleGeneralForumTopicIsHidden
type ToggleGeneralForumTopicIsHiddenOpts struct {
	// Pass true to hide and close the General topic; pass false to unhide it
	IsHidden bool
}

// ToggleGiftIsSavedOpts contains optional parameters for ToggleGiftIsSaved
type ToggleGiftIsSavedOpts struct {
	// Pass true to display the gift on the user's or the channel's profile page; pass false to remove it from the profile page
	IsSaved bool
}

// ToggleGroupCallAreMessagesAllowedOpts contains optional parameters for ToggleGroupCallAreMessagesAllowed
type ToggleGroupCallAreMessagesAllowedOpts struct {
	// New value of the are_messages_allowed setting
	AreMessagesAllowed bool
}

// ToggleGroupCallIsMyVideoEnabledOpts contains optional parameters for ToggleGroupCallIsMyVideoEnabled
type ToggleGroupCallIsMyVideoEnabledOpts struct {
	// Pass true if the current user's video is enabled
	IsMyVideoEnabled bool
}

// ToggleGroupCallIsMyVideoPausedOpts contains optional parameters for ToggleGroupCallIsMyVideoPaused
type ToggleGroupCallIsMyVideoPausedOpts struct {
	// Pass true if the current user's video is paused
	IsMyVideoPaused bool
}

// ToggleGroupCallParticipantIsHandRaisedOpts contains optional parameters for ToggleGroupCallParticipantIsHandRaised
type ToggleGroupCallParticipantIsHandRaisedOpts struct {
	// Pass true if the user's hand needs to be raised. Only self hand can be raised. Requires groupCall.can_be_managed right to lower other's hand
	IsHandRaised bool
}

// ToggleGroupCallParticipantIsMutedOpts contains optional parameters for ToggleGroupCallParticipantIsMuted
type ToggleGroupCallParticipantIsMutedOpts struct {
	// Pass true to mute the user; pass false to unmute them
	IsMuted bool
}

// ToggleGroupCallScreenSharingIsPausedOpts contains optional parameters for ToggleGroupCallScreenSharingIsPaused
type ToggleGroupCallScreenSharingIsPausedOpts struct {
	// Pass true to pause screen sharing; pass false to unpause it
	IsPaused bool
}

// ToggleHasSponsoredMessagesEnabledOpts contains optional parameters for ToggleHasSponsoredMessagesEnabled
type ToggleHasSponsoredMessagesEnabledOpts struct {
	// Pass true to enable sponsored messages for the current user; false to disable them
	HasSponsoredMessagesEnabled bool
}

// ToggleSavedMessagesTopicIsPinnedOpts contains optional parameters for ToggleSavedMessagesTopicIsPinned
type ToggleSavedMessagesTopicIsPinnedOpts struct {
	// Pass true to pin the topic; pass false to unpin it
	IsPinned bool
}

// ToggleSessionCanAcceptCallsOpts contains optional parameters for ToggleSessionCanAcceptCalls
type ToggleSessionCanAcceptCallsOpts struct {
	// Pass true to allow accepting incoming calls by the session; pass false otherwise
	CanAcceptCalls bool
}

// ToggleSessionCanAcceptSecretChatsOpts contains optional parameters for ToggleSessionCanAcceptSecretChats
type ToggleSessionCanAcceptSecretChatsOpts struct {
	// Pass true to allow accepting secret chats by the session; pass false otherwise
	CanAcceptSecretChats bool
}

// ToggleStoryIsPostedToChatPageOpts contains optional parameters for ToggleStoryIsPostedToChatPage
type ToggleStoryIsPostedToChatPageOpts struct {
	// Pass true to make the story accessible after expiration; pass false to make it private
	IsPostedToChatPage bool
}

// ToggleSupergroupCanHaveSponsoredMessagesOpts contains optional parameters for ToggleSupergroupCanHaveSponsoredMessages
type ToggleSupergroupCanHaveSponsoredMessagesOpts struct {
	// The new value of can_have_sponsored_messages
	CanHaveSponsoredMessages bool
}

// ToggleSupergroupHasAggressiveAntiSpamEnabledOpts contains optional parameters for ToggleSupergroupHasAggressiveAntiSpamEnabled
type ToggleSupergroupHasAggressiveAntiSpamEnabledOpts struct {
	// The new value of has_aggressive_anti_spam_enabled
	HasAggressiveAntiSpamEnabled bool
}

// ToggleSupergroupHasAutomaticTranslationOpts contains optional parameters for ToggleSupergroupHasAutomaticTranslation
type ToggleSupergroupHasAutomaticTranslationOpts struct {
	// The new value of has_automatic_translation
	HasAutomaticTranslation bool
}

// ToggleSupergroupHasHiddenMembersOpts contains optional parameters for ToggleSupergroupHasHiddenMembers
type ToggleSupergroupHasHiddenMembersOpts struct {
	// New value of has_hidden_members
	HasHiddenMembers bool
}

// ToggleSupergroupIsAllHistoryAvailableOpts contains optional parameters for ToggleSupergroupIsAllHistoryAvailable
type ToggleSupergroupIsAllHistoryAvailableOpts struct {
	// The new value of is_all_history_available
	IsAllHistoryAvailable bool
}

// ToggleSupergroupIsForumOpts contains optional parameters for ToggleSupergroupIsForum
type ToggleSupergroupIsForumOpts struct {
	// New value of has_forum_tabs; ignored if is_forum is false
	HasForumTabs bool
	// New value of is_forum
	IsForum bool
}

// ToggleSupergroupJoinByRequestOpts contains optional parameters for ToggleSupergroupJoinByRequest
type ToggleSupergroupJoinByRequestOpts struct {
	// Pass true to apply the change to the existing invite links, including primary links
	ApplyToInviteLinks bool
	// New value of join_by_request
	JoinByRequest bool
}

// ToggleSupergroupJoinToSendMessagesOpts contains optional parameters for ToggleSupergroupJoinToSendMessages
type ToggleSupergroupJoinToSendMessagesOpts struct {
	// New value of join_to_send_messages
	JoinToSendMessages bool
}

// ToggleSupergroupSignMessagesOpts contains optional parameters for ToggleSupergroupSignMessages
type ToggleSupergroupSignMessagesOpts struct {
	// New value of show_message_sender
	ShowMessageSender bool
	// New value of sign_messages
	SignMessages bool
}

// ToggleSupergroupUsernameIsActiveOpts contains optional parameters for ToggleSupergroupUsernameIsActive
type ToggleSupergroupUsernameIsActiveOpts struct {
	// Pass true to activate the username; pass false to disable it
	IsActive bool
}

// ToggleUsernameIsActiveOpts contains optional parameters for ToggleUsernameIsActive
type ToggleUsernameIsActiveOpts struct {
	// Pass true to activate the username; pass false to disable it
	IsActive bool
}

// ToggleVideoChatEnabledStartNotificationOpts contains optional parameters for ToggleVideoChatEnabledStartNotification
type ToggleVideoChatEnabledStartNotificationOpts struct {
	// New value of the enabled_start_notification setting
	EnabledStartNotification bool
}

// ToggleVideoChatMuteNewParticipantsOpts contains optional parameters for ToggleVideoChatMuteNewParticipants
type ToggleVideoChatMuteNewParticipantsOpts struct {
	// New value of the mute_new_participants setting
	MuteNewParticipants bool
}

// UpgradeGiftOpts contains optional parameters for UpgradeGift
type UpgradeGiftOpts struct {
	// Pass true to keep the original gift text, sender and receiver in the upgraded gift
	KeepOriginalDetails bool
}

// ValidateOrderInfoOpts contains optional parameters for ValidateOrderInfo
type ValidateOrderInfoOpts struct {
	// Pass true to save the order information
	AllowSave bool
	// The order information, provided by the user; pass null if empty
	OrderInfo *OrderInfo
}

// ViewMessagesOpts contains optional parameters for ViewMessages
type ViewMessagesOpts struct {
	// Pass true to mark as read the specified messages even if the chat is closed
	ForceRead bool
	// Source of the message view; pass null to guess the source based on chat open state
	Source MessageSource
}
