// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package filters

import "github.com/Kanha/Meow"

type (
	// UpdateAccentColors The list of supported accent colors has changed
	UpdateAccentColors func(u *gotdbot.UpdateAccentColors) bool
	// UpdateActiveEmojiReactions The list of active emoji reactions has changed
	UpdateActiveEmojiReactions func(u *gotdbot.UpdateActiveEmojiReactions) bool
	// UpdateActiveGiftAuctions The list of auctions in which the current user participates has changed
	UpdateActiveGiftAuctions func(u *gotdbot.UpdateActiveGiftAuctions) bool
	// UpdateActiveLiveLocationMessages The list of messages with active live location that need to be updated by the application has changed. The list is persistent across application restarts only if the message database is used
	UpdateActiveLiveLocationMessages func(u *gotdbot.UpdateActiveLiveLocationMessages) bool
	// UpdateActiveNotifications Contains active notifications that were shown on previous application launches. This update is sent only if the message database is used. In that case it comes once before any updateNotification and updateNotificationGroup update
	UpdateActiveNotifications func(u *gotdbot.UpdateActiveNotifications) bool
	// UpdateAgeVerificationParameters The parameters for age verification of the current user's account have changed
	UpdateAgeVerificationParameters func(u *gotdbot.UpdateAgeVerificationParameters) bool
	// UpdateAnimatedEmojiMessageClicked Some animated emoji message was clicked and a big animated sticker must be played if the message is visible on the screen. chatActionWatchingAnimations with the text of the message needs to be sent if the sticker is played
	UpdateAnimatedEmojiMessageClicked func(u *gotdbot.UpdateAnimatedEmojiMessageClicked) bool
	// UpdateAnimationSearchParameters The parameters of animation search through getOption("animation_search_bot_username") bot have changed
	UpdateAnimationSearchParameters func(u *gotdbot.UpdateAnimationSearchParameters) bool
	// UpdateApplicationRecaptchaVerificationRequired A request can't be completed unless reCAPTCHA verification is performed; for official mobile applications only.
	UpdateApplicationRecaptchaVerificationRequired func(u *gotdbot.UpdateApplicationRecaptchaVerificationRequired) bool
	// UpdateApplicationVerificationRequired A request can't be completed unless application verification is performed; for official mobile applications only.
	UpdateApplicationVerificationRequired func(u *gotdbot.UpdateApplicationVerificationRequired) bool
	// UpdateAttachmentMenuBots The list of bots added to attachment or side menu has changed
	UpdateAttachmentMenuBots func(u *gotdbot.UpdateAttachmentMenuBots) bool
	// UpdateAuthorizationState The user authorization state has changed
	UpdateAuthorizationState func(u *gotdbot.UpdateAuthorizationState) bool
	// UpdateAutosaveSettings Autosave settings for some type of chats were updated
	UpdateAutosaveSettings func(u *gotdbot.UpdateAutosaveSettings) bool
	// UpdateAvailableMessageEffects The list of available message effects has changed
	UpdateAvailableMessageEffects func(u *gotdbot.UpdateAvailableMessageEffects) bool
	// UpdateBasicGroup Some data of a basic group has changed. This update is guaranteed to come before the basic group identifier is returned to the application
	UpdateBasicGroup func(u *gotdbot.UpdateBasicGroup) bool
	// UpdateBasicGroupFullInfo Some data in basicGroupFullInfo has been changed
	UpdateBasicGroupFullInfo func(u *gotdbot.UpdateBasicGroupFullInfo) bool
	// UpdateBusinessConnection A business connection has changed; for bots only
	UpdateBusinessConnection func(u *gotdbot.UpdateBusinessConnection) bool
	// UpdateBusinessMessageEdited A message in a business account was edited; for bots only
	UpdateBusinessMessageEdited func(u *gotdbot.UpdateBusinessMessageEdited) bool
	// UpdateBusinessMessagesDeleted Messages in a business account were deleted; for bots only
	UpdateBusinessMessagesDeleted func(u *gotdbot.UpdateBusinessMessagesDeleted) bool
	// UpdateCall New call was created or information about a call was updated
	UpdateCall func(u *gotdbot.UpdateCall) bool
	// UpdateChatAccentColors Chat accent colors have changed
	UpdateChatAccentColors func(u *gotdbot.UpdateChatAccentColors) bool
	// UpdateChatAction A message sender activity in the chat has changed
	UpdateChatAction func(u *gotdbot.UpdateChatAction) bool
	// UpdateChatActionBar The chat action bar was changed
	UpdateChatActionBar func(u *gotdbot.UpdateChatActionBar) bool
	// UpdateChatActiveStories The list of active stories posted by a specific chat has changed
	UpdateChatActiveStories func(u *gotdbot.UpdateChatActiveStories) bool
	// UpdateChatAddedToList A chat was added to a chat list
	UpdateChatAddedToList func(u *gotdbot.UpdateChatAddedToList) bool
	// UpdateChatAvailableReactions The chat available reactions were changed
	UpdateChatAvailableReactions func(u *gotdbot.UpdateChatAvailableReactions) bool
	// UpdateChatBackground The chat background was changed
	UpdateChatBackground func(u *gotdbot.UpdateChatBackground) bool
	// UpdateChatBlockList A chat was blocked or unblocked
	UpdateChatBlockList func(u *gotdbot.UpdateChatBlockList) bool
	// UpdateChatBoost A chat boost has changed; for bots only
	UpdateChatBoost func(u *gotdbot.UpdateChatBoost) bool
	// UpdateChatBusinessBotManageBar The bar for managing business bot was changed in a chat
	UpdateChatBusinessBotManageBar func(u *gotdbot.UpdateChatBusinessBotManageBar) bool
	// UpdateChatDefaultDisableNotification The value of the default disable_notification parameter, used when a message is sent to the chat, was changed
	UpdateChatDefaultDisableNotification func(u *gotdbot.UpdateChatDefaultDisableNotification) bool
	// UpdateChatDraftMessage A chat draft has changed. Be aware that the update may come in the currently opened chat but with old content of the draft. If the user has changed the content of the draft, this update mustn't be applied
	UpdateChatDraftMessage func(u *gotdbot.UpdateChatDraftMessage) bool
	// UpdateChatEmojiStatus Chat emoji status has changed
	UpdateChatEmojiStatus func(u *gotdbot.UpdateChatEmojiStatus) bool
	// UpdateChatFolders The list of chat folders or a chat folder has changed
	UpdateChatFolders func(u *gotdbot.UpdateChatFolders) bool
	// UpdateChatHasProtectedContent A chat content was allowed or restricted for saving
	UpdateChatHasProtectedContent func(u *gotdbot.UpdateChatHasProtectedContent) bool
	// UpdateChatHasScheduledMessages A chat's has_scheduled_messages field has changed
	UpdateChatHasScheduledMessages func(u *gotdbot.UpdateChatHasScheduledMessages) bool
	// UpdateChatHasWelcomeMessages A chat's has_welcome_messages field has changed
	UpdateChatHasWelcomeMessages func(u *gotdbot.UpdateChatHasWelcomeMessages) bool
	// UpdateChatIsMarkedAsUnread A chat was marked as unread or was read
	UpdateChatIsMarkedAsUnread func(u *gotdbot.UpdateChatIsMarkedAsUnread) bool
	// UpdateChatIsTranslatable Translation of chat messages was enabled or disabled
	UpdateChatIsTranslatable func(u *gotdbot.UpdateChatIsTranslatable) bool
	// UpdateChatJoinResult A join request from the user was completed
	UpdateChatJoinResult func(u *gotdbot.UpdateChatJoinResult) bool
	// UpdateChatLastMessage The last message of a chat was changed
	UpdateChatLastMessage func(u *gotdbot.UpdateChatLastMessage) bool
	// UpdateChatMember User rights changed in a chat; for bots only
	UpdateChatMember func(u *gotdbot.UpdateChatMember) bool
	// UpdateChatMessageAutoDeleteTime The message auto-delete or self-destruct timer setting for a chat was changed
	UpdateChatMessageAutoDeleteTime func(u *gotdbot.UpdateChatMessageAutoDeleteTime) bool
	// UpdateChatMessageSender The message sender that is selected to send messages in a chat has changed
	UpdateChatMessageSender func(u *gotdbot.UpdateChatMessageSender) bool
	// UpdateChatNotificationSettings Notification settings for a chat were changed
	UpdateChatNotificationSettings func(u *gotdbot.UpdateChatNotificationSettings) bool
	// UpdateChatOnlineMemberCount The number of online group members has changed. This update with non-zero number of online group members is sent only for currently opened chats.
	UpdateChatOnlineMemberCount func(u *gotdbot.UpdateChatOnlineMemberCount) bool
	// UpdateChatPendingJoinRequests The chat pending join requests were changed
	UpdateChatPendingJoinRequests func(u *gotdbot.UpdateChatPendingJoinRequests) bool
	// UpdateChatPermissions Chat permissions were changed
	UpdateChatPermissions func(u *gotdbot.UpdateChatPermissions) bool
	// UpdateChatPhoto A chat photo was changed
	UpdateChatPhoto func(u *gotdbot.UpdateChatPhoto) bool
	// UpdateChatPosition The position of a chat in a chat list has changed. An updateChatLastMessage or updateChatDraftMessage update might be sent instead of the update
	UpdateChatPosition func(u *gotdbot.UpdateChatPosition) bool
	// UpdateChatReadInbox Incoming messages were read or the number of unread messages has been changed
	UpdateChatReadInbox func(u *gotdbot.UpdateChatReadInbox) bool
	// UpdateChatReadOutbox Outgoing messages were read
	UpdateChatReadOutbox func(u *gotdbot.UpdateChatReadOutbox) bool
	// UpdateChatRemovedFromList A chat was removed from a chat list
	UpdateChatRemovedFromList func(u *gotdbot.UpdateChatRemovedFromList) bool
	// UpdateChatReplyMarkup The chat reply markup was changed
	UpdateChatReplyMarkup func(u *gotdbot.UpdateChatReplyMarkup) bool
	// UpdateChatRevenueAmount The revenue earned from sponsored messages in a chat has changed. If chat revenue screen is opened, then getChatRevenueTransactions may be called to fetch new transactions
	UpdateChatRevenueAmount func(u *gotdbot.UpdateChatRevenueAmount) bool
	// UpdateChatTheme The chat theme was changed
	UpdateChatTheme func(u *gotdbot.UpdateChatTheme) bool
	// UpdateChatTitle The title of a chat was changed
	UpdateChatTitle func(u *gotdbot.UpdateChatTitle) bool
	// UpdateChatUnreadMentionCount The chat unread_mention_count has changed
	UpdateChatUnreadMentionCount func(u *gotdbot.UpdateChatUnreadMentionCount) bool
	// UpdateChatUnreadPollVoteCount The chat unread_poll_vote_count has changed
	UpdateChatUnreadPollVoteCount func(u *gotdbot.UpdateChatUnreadPollVoteCount) bool
	// UpdateChatUnreadReactionCount The chat unread_reaction_count has changed
	UpdateChatUnreadReactionCount func(u *gotdbot.UpdateChatUnreadReactionCount) bool
	// UpdateChatVideoChat A chat video chat state has changed
	UpdateChatVideoChat func(u *gotdbot.UpdateChatVideoChat) bool
	// UpdateChatViewAsTopics A chat default appearance has changed
	UpdateChatViewAsTopics func(u *gotdbot.UpdateChatViewAsTopics) bool
	// UpdateChatWelcomeMessages The list of welcome messages of a chat has changed
	UpdateChatWelcomeMessages func(u *gotdbot.UpdateChatWelcomeMessages) bool
	// UpdateCommunity Some data of a community has changed. This update is guaranteed to come before the community identifier is returned to the application
	UpdateCommunity func(u *gotdbot.UpdateCommunity) bool
	// UpdateCommunityFullInfo Some data in communityFullInfo has been changed
	UpdateCommunityFullInfo func(u *gotdbot.UpdateCommunityFullInfo) bool
	// UpdateConnectionState The connection state has changed. This update must be used only to show a human-readable description of the connection state
	UpdateConnectionState func(u *gotdbot.UpdateConnectionState) bool
	// UpdateContactCloseBirthdays The list of contacts that had birthdays recently or will have birthday soon has changed
	UpdateContactCloseBirthdays func(u *gotdbot.UpdateContactCloseBirthdays) bool
	// UpdateDefaultBackground The default background has changed
	UpdateDefaultBackground func(u *gotdbot.UpdateDefaultBackground) bool
	// UpdateDefaultPaidReactionType The type of default paid reaction has changed
	UpdateDefaultPaidReactionType func(u *gotdbot.UpdateDefaultPaidReactionType) bool
	// UpdateDefaultReactionType The type of default reaction has changed
	UpdateDefaultReactionType func(u *gotdbot.UpdateDefaultReactionType) bool
	// UpdateDeleteMessages Some messages were deleted
	UpdateDeleteMessages func(u *gotdbot.UpdateDeleteMessages) bool
	// UpdateDiceEmojis The list of supported dice emojis has changed
	UpdateDiceEmojis func(u *gotdbot.UpdateDiceEmojis) bool
	// UpdateDirectMessagesChatTopic Basic information about a topic in a channel direct messages chat administered by the current user has changed. This update is guaranteed to come before the topic identifier is returned to the application
	UpdateDirectMessagesChatTopic func(u *gotdbot.UpdateDirectMessagesChatTopic) bool
	// UpdateEmojiChatThemes The list of available emoji chat themes has changed
	UpdateEmojiChatThemes func(u *gotdbot.UpdateEmojiChatThemes) bool
	// UpdateFavoriteStickers The list of favorite stickers was updated
	UpdateFavoriteStickers func(u *gotdbot.UpdateFavoriteStickers) bool
	// UpdateFile Information about a file was updated
	UpdateFile func(u *gotdbot.UpdateFile) bool
	// UpdateFileAddedToDownloads A file was added to the file download list. This update is sent only after file download list is loaded for the first time
	UpdateFileAddedToDownloads func(u *gotdbot.UpdateFileAddedToDownloads) bool
	// UpdateFileDownload A file download was changed. This update is sent only after file download list is loaded for the first time
	UpdateFileDownload func(u *gotdbot.UpdateFileDownload) bool
	// UpdateFileDownloads The state of the file download list has changed
	UpdateFileDownloads func(u *gotdbot.UpdateFileDownloads) bool
	// UpdateFileGenerationStart The file generation process needs to be started by the application. Use setFileGenerationProgress and finishFileGeneration to generate the file
	UpdateFileGenerationStart func(u *gotdbot.UpdateFileGenerationStart) bool
	// UpdateFileGenerationStop File generation is no longer needed
	UpdateFileGenerationStop func(u *gotdbot.UpdateFileGenerationStop) bool
	// UpdateFileRemovedFromDownloads A file was removed from the file download list. This update is sent only after file download list is loaded for the first time
	UpdateFileRemovedFromDownloads func(u *gotdbot.UpdateFileRemovedFromDownloads) bool
	// UpdateForumTopic Information about a topic in a forum chat was changed
	UpdateForumTopic func(u *gotdbot.UpdateForumTopic) bool
	// UpdateForumTopicInfo Basic information about a topic in a forum chat was changed
	UpdateForumTopicInfo func(u *gotdbot.UpdateForumTopicInfo) bool
	// UpdateFreezeState The freeze state of the current user's account has changed
	UpdateFreezeState func(u *gotdbot.UpdateFreezeState) bool
	// UpdateGiftAuctionState State of a gift auction was updated
	UpdateGiftAuctionState func(u *gotdbot.UpdateGiftAuctionState) bool
	// UpdateGramRevenueStatus The TON Gram revenue earned by the current user has changed. If Gram transaction screen of the chat is opened, then getTonTransactions may be called to fetch new transactions
	UpdateGramRevenueStatus func(u *gotdbot.UpdateGramRevenueStatus) bool
	// UpdateGroupCall Information about a group call was updated
	UpdateGroupCall func(u *gotdbot.UpdateGroupCall) bool
	// UpdateGroupCallMessageLevels The levels of live story group call messages have changed
	UpdateGroupCallMessageLevels func(u *gotdbot.UpdateGroupCallMessageLevels) bool
	// UpdateGroupCallMessagesDeleted Some group call messages were deleted
	UpdateGroupCallMessagesDeleted func(u *gotdbot.UpdateGroupCallMessagesDeleted) bool
	// UpdateGroupCallMessageSendFailed A group call message failed to send
	UpdateGroupCallMessageSendFailed func(u *gotdbot.UpdateGroupCallMessageSendFailed) bool
	// UpdateGroupCallParticipant Information about a group call participant was changed. The updates are sent only after the group call is received through getGroupCall and only if the call is joined or being joined
	UpdateGroupCallParticipant func(u *gotdbot.UpdateGroupCallParticipant) bool
	// UpdateGroupCallParticipants The list of group call participants that can send and receive encrypted call data has changed; for group calls not bound to a chat only
	UpdateGroupCallParticipants func(u *gotdbot.UpdateGroupCallParticipants) bool
	// UpdateGroupCallVerificationState The verification state of an encrypted group call has changed; for group calls not bound to a chat only
	UpdateGroupCallVerificationState func(u *gotdbot.UpdateGroupCallVerificationState) bool
	// UpdateHavePendingNotifications Describes whether there are some pending notification updates. Can be used to prevent application from killing, while there are some pending notifications
	UpdateHavePendingNotifications func(u *gotdbot.UpdateHavePendingNotifications) bool
	// UpdateInstalledStickerSets The list of installed sticker sets was updated
	UpdateInstalledStickerSets func(u *gotdbot.UpdateInstalledStickerSets) bool
	// UpdateLanguagePackStrings Some language pack strings have been updated
	UpdateLanguagePackStrings func(u *gotdbot.UpdateLanguagePackStrings) bool
	// UpdateLiveStoryTopDonors The list of top donors in live story group call has changed
	UpdateLiveStoryTopDonors func(u *gotdbot.UpdateLiveStoryTopDonors) bool
	// UpdateManagedBot A bot that can be managed by the current bot was created or updated; for bots only
	UpdateManagedBot func(u *gotdbot.UpdateManagedBot) bool
	// UpdateMessageContainsUnreadPollVotes Unread votes were added or removed from a poll message
	UpdateMessageContainsUnreadPollVotes func(u *gotdbot.UpdateMessageContainsUnreadPollVotes) bool
	// UpdateMessageContent The message content has changed
	UpdateMessageContent func(u *gotdbot.UpdateMessageContent) bool
	// UpdateMessageContentOpened The message content was opened. Updates voice note messages to "listened", video note messages to "viewed" and starts the self-destruct timer
	UpdateMessageContentOpened func(u *gotdbot.UpdateMessageContentOpened) bool
	// UpdateMessageEdited A message was edited. Changes in the message content will come in a separate updateMessageContent
	UpdateMessageEdited func(u *gotdbot.UpdateMessageEdited) bool
	// UpdateMessageEphemeralContent The message ephemeral content has changed
	UpdateMessageEphemeralContent func(u *gotdbot.UpdateMessageEphemeralContent) bool
	// UpdateMessageFactCheck A fact-check added to a message was changed
	UpdateMessageFactCheck func(u *gotdbot.UpdateMessageFactCheck) bool
	// UpdateMessageInteractionInfo The information about interactions with a message has changed
	UpdateMessageInteractionInfo func(u *gotdbot.UpdateMessageInteractionInfo) bool
	// UpdateMessageIsPinned The message pinned state was changed
	UpdateMessageIsPinned func(u *gotdbot.UpdateMessageIsPinned) bool
	// UpdateMessageLiveLocationViewed A message with a live location was viewed. When the update is received, the application is expected to update the live location
	UpdateMessageLiveLocationViewed func(u *gotdbot.UpdateMessageLiveLocationViewed) bool
	// UpdateMessageMentionRead A message with an unread mention was read
	UpdateMessageMentionRead func(u *gotdbot.UpdateMessageMentionRead) bool
	// UpdateMessageReaction User changed its reactions on a message with public reactions; for bots only
	UpdateMessageReaction func(u *gotdbot.UpdateMessageReaction) bool
	// UpdateMessageReactions Reactions added to a message with anonymous reactions have changed; for bots only
	UpdateMessageReactions func(u *gotdbot.UpdateMessageReactions) bool
	// UpdateMessageSendAcknowledged A request to send a message has reached the Telegram server. This doesn't mean that the message will be sent successfully.
	UpdateMessageSendAcknowledged func(u *gotdbot.UpdateMessageSendAcknowledged) bool
	// UpdateMessageSendFailed A message failed to send. Be aware that some messages being sent can be irrecoverably deleted, in which case updateDeleteMessages will be received instead of this update
	UpdateMessageSendFailed func(u *gotdbot.UpdateMessageSendFailed) bool
	// UpdateMessageSendSucceeded A message has been successfully sent
	UpdateMessageSendSucceeded func(u *gotdbot.UpdateMessageSendSucceeded) bool
	// UpdateMessageSuggestedPostInfo Information about suggested post of a message was changed
	UpdateMessageSuggestedPostInfo func(u *gotdbot.UpdateMessageSuggestedPostInfo) bool
	// UpdateMessageUnreadReactions The list of unread reactions added to a message was changed
	UpdateMessageUnreadReactions func(u *gotdbot.UpdateMessageUnreadReactions) bool
	// UpdateNewBusinessCallbackQuery A new incoming callback query from a business message; for bots only
	UpdateNewBusinessCallbackQuery func(u *gotdbot.UpdateNewBusinessCallbackQuery) bool
	// UpdateNewBusinessMessage A new message was added to a business account; for bots only
	UpdateNewBusinessMessage func(u *gotdbot.UpdateNewBusinessMessage) bool
	// UpdateNewCallbackQuery A new incoming callback query; for bots only
	UpdateNewCallbackQuery func(u *gotdbot.UpdateNewCallbackQuery) bool
	// UpdateNewCallSignalingData New call signaling data arrived
	UpdateNewCallSignalingData func(u *gotdbot.UpdateNewCallSignalingData) bool
	// UpdateNewChat A new chat has been loaded/created. This update is guaranteed to come before the chat identifier is returned to the application. The chat field changes will be reported through separate updates
	UpdateNewChat func(u *gotdbot.UpdateNewChat) bool
	// UpdateNewChatJoinRequest A user sent a join request to a chat; for bots only
	UpdateNewChatJoinRequest func(u *gotdbot.UpdateNewChatJoinRequest) bool
	// UpdateNewChosenInlineResult The user has chosen a result of an inline query; for bots only
	UpdateNewChosenInlineResult func(u *gotdbot.UpdateNewChosenInlineResult) bool
	// UpdateNewCustomEvent A new incoming event; for bots only
	UpdateNewCustomEvent func(u *gotdbot.UpdateNewCustomEvent) bool
	// UpdateNewCustomQuery A new incoming query; for bots only
	UpdateNewCustomQuery func(u *gotdbot.UpdateNewCustomQuery) bool
	// UpdateNewGroupCallMessage A new message was received in a group call
	UpdateNewGroupCallMessage func(u *gotdbot.UpdateNewGroupCallMessage) bool
	// UpdateNewGroupCallPaidReaction A new paid reaction was received in a live story group call
	UpdateNewGroupCallPaidReaction func(u *gotdbot.UpdateNewGroupCallPaidReaction) bool
	// UpdateNewGuestQuery A new incoming guest query; for bots only
	UpdateNewGuestQuery func(u *gotdbot.UpdateNewGuestQuery) bool
	// UpdateNewInlineCallbackQuery A new incoming callback query from a message sent via a bot; for bots only
	UpdateNewInlineCallbackQuery func(u *gotdbot.UpdateNewInlineCallbackQuery) bool
	// UpdateNewInlineQuery A new incoming inline query; for bots only
	UpdateNewInlineQuery func(u *gotdbot.UpdateNewInlineQuery) bool
	// UpdateNewMessage A new message was received; can also be an outgoing message
	UpdateNewMessage func(u *gotdbot.UpdateNewMessage) bool
	// UpdateNewOauthRequest An OAuth authorization request was received
	UpdateNewOauthRequest func(u *gotdbot.UpdateNewOauthRequest) bool
	// UpdateNewPreCheckoutQuery A new incoming pre-checkout query; for bots only. Contains full information about a checkout
	UpdateNewPreCheckoutQuery func(u *gotdbot.UpdateNewPreCheckoutQuery) bool
	// UpdateNewShippingQuery A new incoming shipping query; for bots only. Only for invoices with flexible price
	UpdateNewShippingQuery func(u *gotdbot.UpdateNewShippingQuery) bool
	// UpdateNotification A notification was changed
	UpdateNotification func(u *gotdbot.UpdateNotification) bool
	// UpdateNotificationGroup A list of active notifications in a notification group has changed
	UpdateNotificationGroup func(u *gotdbot.UpdateNotificationGroup) bool
	// UpdateOption An option changed its value
	UpdateOption func(u *gotdbot.UpdateOption) bool
	// UpdateOwnedGramCount The number of TON Grams owned by the current user has changed
	UpdateOwnedGramCount func(u *gotdbot.UpdateOwnedGramCount) bool
	// UpdateOwnedStarCount The number of Telegram Stars owned by the current user has changed
	UpdateOwnedStarCount func(u *gotdbot.UpdateOwnedStarCount) bool
	// UpdatePaidMediaPurchased Paid media were purchased by a user; for bots only
	UpdatePaidMediaPurchased func(u *gotdbot.UpdatePaidMediaPurchased) bool
	// UpdatePendingMessage A new pending text or rich message was received in a chat with a bot. The message must be shown in the chat for at most getOption("pending_text_message_period") seconds,
	UpdatePendingMessage func(u *gotdbot.UpdatePendingMessage) bool
	// UpdatePoll A poll was updated; for bots only
	UpdatePoll func(u *gotdbot.UpdatePoll) bool
	// UpdatePollAnswer A user changed the answer to a poll; for bots only
	UpdatePollAnswer func(u *gotdbot.UpdatePollAnswer) bool
	// UpdateProfileAccentColors The list of supported accent colors for user profiles has changed
	UpdateProfileAccentColors func(u *gotdbot.UpdateProfileAccentColors) bool
	// UpdateQuickReplyShortcut Basic information about a quick reply shortcut has changed. This update is guaranteed to come before the quick shortcut name is returned to the application
	UpdateQuickReplyShortcut func(u *gotdbot.UpdateQuickReplyShortcut) bool
	// UpdateQuickReplyShortcutDeleted A quick reply shortcut and all its messages were deleted
	UpdateQuickReplyShortcutDeleted func(u *gotdbot.UpdateQuickReplyShortcutDeleted) bool
	// UpdateQuickReplyShortcutMessages The list of quick reply shortcut messages has changed
	UpdateQuickReplyShortcutMessages func(u *gotdbot.UpdateQuickReplyShortcutMessages) bool
	// UpdateQuickReplyShortcuts The list of quick reply shortcuts has changed
	UpdateQuickReplyShortcuts func(u *gotdbot.UpdateQuickReplyShortcuts) bool
	// UpdateReactionNotificationSettings Notification settings for reactions were updated
	UpdateReactionNotificationSettings func(u *gotdbot.UpdateReactionNotificationSettings) bool
	// UpdateRecentStickers The list of recently used stickers was updated
	UpdateRecentStickers func(u *gotdbot.UpdateRecentStickers) bool
	// Updates Contains a list of updates
	Updates func(u *gotdbot.Updates) bool
	// UpdateSavedAnimations The list of saved animations was updated
	UpdateSavedAnimations func(u *gotdbot.UpdateSavedAnimations) bool
	// UpdateSavedMessagesTags Tags used in Saved Messages or a Saved Messages topic have changed
	UpdateSavedMessagesTags func(u *gotdbot.UpdateSavedMessagesTags) bool
	// UpdateSavedMessagesTopic Basic information about a Saved Messages topic has changed. This update is guaranteed to come before the topic identifier is returned to the application
	UpdateSavedMessagesTopic func(u *gotdbot.UpdateSavedMessagesTopic) bool
	// UpdateSavedMessagesTopicCount Number of Saved Messages topics has changed
	UpdateSavedMessagesTopicCount func(u *gotdbot.UpdateSavedMessagesTopicCount) bool
	// UpdateSavedNotificationSounds The list of saved notification sounds was updated. This update may not be sent until information about a notification sound was requested for the first time
	UpdateSavedNotificationSounds func(u *gotdbot.UpdateSavedNotificationSounds) bool
	// UpdateScopeNotificationSettings Notification settings for some type of chats were updated
	UpdateScopeNotificationSettings func(u *gotdbot.UpdateScopeNotificationSettings) bool
	// UpdateSecretChat Some data of a secret chat has changed. This update is guaranteed to come before the secret chat identifier is returned to the application
	UpdateSecretChat func(u *gotdbot.UpdateSecretChat) bool
	// UpdateServiceNotification A service notification from the server was received. Upon receiving this the application must show a popup with the content of the notification
	UpdateServiceNotification func(u *gotdbot.UpdateServiceNotification) bool
	// UpdateSpeechRecognitionTrial The parameters of speech recognition without Telegram Premium subscription have changed
	UpdateSpeechRecognitionTrial func(u *gotdbot.UpdateSpeechRecognitionTrial) bool
	// UpdateSpeedLimitNotification Download or upload file speed for the user was limited, but it can be restored by subscription to Telegram Premium. The notification can be postponed until a file being downloaded or uploaded is visible to the user.
	UpdateSpeedLimitNotification func(u *gotdbot.UpdateSpeedLimitNotification) bool
	// UpdateStakeDiceState The stake dice state has changed
	UpdateStakeDiceState func(u *gotdbot.UpdateStakeDiceState) bool
	// UpdateStarRevenueStatus The Telegram Star revenue earned by a user or a chat has changed. If Telegram Star transaction screen of the chat is opened, then getStarTransactions may be called to fetch new transactions
	UpdateStarRevenueStatus func(u *gotdbot.UpdateStarRevenueStatus) bool
	// UpdateStickerSet A sticker set has changed
	UpdateStickerSet func(u *gotdbot.UpdateStickerSet) bool
	// UpdateStopMessageDraft A message draft generation was stopped by the user
	UpdateStopMessageDraft func(u *gotdbot.UpdateStopMessageDraft) bool
	// UpdateStory A story was changed
	UpdateStory func(u *gotdbot.UpdateStory) bool
	// UpdateStoryDeleted A story became inaccessible
	UpdateStoryDeleted func(u *gotdbot.UpdateStoryDeleted) bool
	// UpdateStoryListChatCount Number of chats in a story list has changed
	UpdateStoryListChatCount func(u *gotdbot.UpdateStoryListChatCount) bool
	// UpdateStoryPostFailed A story failed to post. If the story posting is canceled, then updateStoryDeleted will be received instead of this update
	UpdateStoryPostFailed func(u *gotdbot.UpdateStoryPostFailed) bool
	// UpdateStoryPostSucceeded A story has been successfully posted
	UpdateStoryPostSucceeded func(u *gotdbot.UpdateStoryPostSucceeded) bool
	// UpdateStoryStealthMode Story stealth mode settings have changed
	UpdateStoryStealthMode func(u *gotdbot.UpdateStoryStealthMode) bool
	// UpdateSuggestedActions The list of suggested to the user actions has changed
	UpdateSuggestedActions func(u *gotdbot.UpdateSuggestedActions) bool
	// UpdateSupergroup Some data of a supergroup or a channel has changed. This update is guaranteed to come before the supergroup identifier is returned to the application
	UpdateSupergroup func(u *gotdbot.UpdateSupergroup) bool
	// UpdateSupergroupFullInfo Some data in supergroupFullInfo has been changed
	UpdateSupergroupFullInfo func(u *gotdbot.UpdateSupergroupFullInfo) bool
	// UpdateTermsOfService New terms of service must be accepted by the user. If the terms of service are declined, then the deleteAccount method must be called with the reason "Decline ToS update"
	UpdateTermsOfService func(u *gotdbot.UpdateTermsOfService) bool
	// UpdateTextCompositionStyles The styles supported for text composition have changed
	UpdateTextCompositionStyles func(u *gotdbot.UpdateTextCompositionStyles) bool
	// UpdateTopicMessageCount Number of messages in a topic has changed; for Saved Messages and channel direct messages chat topics only
	UpdateTopicMessageCount func(u *gotdbot.UpdateTopicMessageCount) bool
	// UpdateTrendingStickerSets The list of trending sticker sets was updated or some of them were viewed
	UpdateTrendingStickerSets func(u *gotdbot.UpdateTrendingStickerSets) bool
	// UpdateTrustedMiniAppBots Lists of bots which Mini Apps must be allowed to read text from clipboard and must be opened without a warning
	UpdateTrustedMiniAppBots func(u *gotdbot.UpdateTrustedMiniAppBots) bool
	// UpdateUnconfirmedSession The first unconfirmed session has changed
	UpdateUnconfirmedSession func(u *gotdbot.UpdateUnconfirmedSession) bool
	// UpdateUnreadChatCount Number of unread chats, i.e. with unread messages or marked as unread, has changed. This update is sent only if the message database is used
	UpdateUnreadChatCount func(u *gotdbot.UpdateUnreadChatCount) bool
	// UpdateUnreadMessageCount Number of unread messages in a chat list has changed. This update is sent only if the message database is used
	UpdateUnreadMessageCount func(u *gotdbot.UpdateUnreadMessageCount) bool
	// UpdateUser Some data of a user has changed. This update is guaranteed to come before the user identifier is returned to the application
	UpdateUser func(u *gotdbot.UpdateUser) bool
	// UpdateUserFullInfo Some data in userFullInfo has been changed
	UpdateUserFullInfo func(u *gotdbot.UpdateUserFullInfo) bool
	// UpdateUserPrivacySettingRules Some privacy setting rules have been changed
	UpdateUserPrivacySettingRules func(u *gotdbot.UpdateUserPrivacySettingRules) bool
	// UpdateUserStatus The user went online or offline
	UpdateUserStatus func(u *gotdbot.UpdateUserStatus) bool
	// UpdateUserSubscription Subscription of a user to the bot was changed; for bots only
	UpdateUserSubscription func(u *gotdbot.UpdateUserSubscription) bool
	// UpdateVideoPublished An automatically scheduled message with video has been successfully sent after conversion
	UpdateVideoPublished func(u *gotdbot.UpdateVideoPublished) bool
	// UpdateWebAppMessageSent A message was sent by an opened Web App, so the Web App needs to be closed
	UpdateWebAppMessageSent func(u *gotdbot.UpdateWebAppMessageSent) bool
	// UpdateWebBrowserSettings Web browser settings have been updated
	UpdateWebBrowserSettings func(u *gotdbot.UpdateWebBrowserSettings) bool
	// Message is a filter for Message type
	Message func(msg *gotdbot.Message) bool
)
